//
// Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
//
// On Wed Feb 12 20:20:13 EST 2020
//
//
// Ports:
// Name                         I/O  size props
// obtain_rq_get                  O    69 reg
// RDY_obtain_rq_get              O     1 reg
// RDY_send_rs_put                O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// send_rs_put                    I    32 reg
// EN_send_rs_put                 I     1
// EN_obtain_rq_get               I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTop(CLK,
	     RST_N,

	     EN_obtain_rq_get,
	     obtain_rq_get,
	     RDY_obtain_rq_get,

	     send_rs_put,
	     EN_send_rs_put,
	     RDY_send_rs_put);
  input  CLK;
  input  RST_N;

  // actionvalue method obtain_rq_get
  input  EN_obtain_rq_get;
  output [68 : 0] obtain_rq_get;
  output RDY_obtain_rq_get;

  // action method send_rs_put
  input  [31 : 0] send_rs_put;
  input  EN_send_rs_put;
  output RDY_send_rs_put;

  // signals for module outputs
  wire [68 : 0] obtain_rq_get;
  wire RDY_obtain_rq_get, RDY_send_rs_put;

  // inlined wires
  reg [164 : 0] proc_m6_pff_rv$port1__write_1;
  wire [196 : 0] proc_m9_pff_rv$port1__read,
		 proc_m9_pff_rv$port1__write_1,
		 proc_m9_pff_rv$port2__read;
  wire [164 : 0] proc_m6_pff_rv$port1__read, proc_m6_pff_rv$port2__read;
  wire [57 : 0] proc_m3_pff_rv$port1__read,
		proc_m3_pff_rv$port1__write_1,
		proc_m3_pff_rv$port2__read,
		proc_m3_pff_rv$port3__read;
  wire [24 : 0] proc_m7_pff_rv$port0__write_1,
		proc_m7_pff_rv$port1__read,
		proc_m7_pff_rv$port2__read;
  wire proc_m3_pff_rv$EN_port0__write,
       proc_m6_pff_rv$EN_port0__write,
       proc_m6_pff_rv$EN_port1__write,
       proc_m7_pff_rv$EN_port0__write,
       proc_m9_pff_rv$EN_port0__write,
       proc_m9_pff_rv$EN_port1__write;

  // register proc_m10_fEpoch
  reg proc_m10_fEpoch;
  wire proc_m10_fEpoch$D_IN, proc_m10_fEpoch$EN;

  // register proc_m10_pc
  reg [11 : 0] proc_m10_pc;
  wire [11 : 0] proc_m10_pc$D_IN;
  wire proc_m10_pc$EN;

  // register proc_m10_pcUpdated
  reg proc_m10_pcUpdated;
  wire proc_m10_pcUpdated$D_IN, proc_m10_pcUpdated$EN;

  // register proc_m10_pinit
  reg proc_m10_pinit;
  wire proc_m10_pinit$D_IN, proc_m10_pinit$EN;

  // register proc_m10_pinitRq
  reg proc_m10_pinitRq;
  wire proc_m10_pinitRq$D_IN, proc_m10_pinitRq$EN;

  // register proc_m10_pinitRqOfs
  reg [9 : 0] proc_m10_pinitRqOfs;
  wire [9 : 0] proc_m10_pinitRqOfs$D_IN;
  wire proc_m10_pinitRqOfs$EN;

  // register proc_m10_pinitRsOfs
  reg [9 : 0] proc_m10_pinitRsOfs;
  wire [9 : 0] proc_m10_pinitRsOfs$D_IN;
  wire proc_m10_pinitRsOfs$EN;

  // register proc_m13_lastPc
  reg [11 : 0] proc_m13_lastPc;
  wire [11 : 0] proc_m13_lastPc$D_IN;
  wire proc_m13_lastPc$EN;

  // register proc_m13_stall
  reg proc_m13_stall;
  wire proc_m13_stall$D_IN, proc_m13_stall$EN;

  // register proc_m13_stalled
  reg [163 : 0] proc_m13_stalled;
  wire [163 : 0] proc_m13_stalled$D_IN;
  wire proc_m13_stalled$EN;

  // register proc_m1_readRq
  reg proc_m1_readRq;
  wire proc_m1_readRq$D_IN, proc_m1_readRq$EN;

  // register proc_m2_btbTags
  reg [55 : 0] proc_m2_btbTags;
  wire [55 : 0] proc_m2_btbTags$D_IN;
  wire proc_m2_btbTags$EN;

  // register proc_m2_btbTargets
  reg [79 : 0] proc_m2_btbTargets;
  wire [79 : 0] proc_m2_btbTargets$D_IN;
  wire proc_m2_btbTargets$EN;

  // register proc_m2_btbValid
  reg [7 : 0] proc_m2_btbValid;
  wire [7 : 0] proc_m2_btbValid$D_IN;
  wire proc_m2_btbValid$EN;

  // register proc_m3_pff_rv
  reg [57 : 0] proc_m3_pff_rv;
  wire [57 : 0] proc_m3_pff_rv$D_IN;
  wire proc_m3_pff_rv$EN;

  // register proc_m4_rf
  reg [1023 : 0] proc_m4_rf;
  wire [1023 : 0] proc_m4_rf$D_IN;
  wire proc_m4_rf$EN;

  // register proc_m5_sbFlags
  reg [31 : 0] proc_m5_sbFlags;
  reg [31 : 0] proc_m5_sbFlags$D_IN;
  wire proc_m5_sbFlags$EN;

  // register proc_m6_pff_rv
  reg [164 : 0] proc_m6_pff_rv;
  wire [164 : 0] proc_m6_pff_rv$D_IN;
  wire proc_m6_pff_rv$EN;

  // register proc_m7_pff_rv
  reg [24 : 0] proc_m7_pff_rv;
  wire [24 : 0] proc_m7_pff_rv$D_IN;
  wire proc_m7_pff_rv$EN;

  // register proc_m8_eEpoch
  reg proc_m8_eEpoch;
  wire proc_m8_eEpoch$D_IN, proc_m8_eEpoch$EN;

  // register proc_m9_pff_rv
  reg [196 : 0] proc_m9_pff_rv;
  wire [196 : 0] proc_m9_pff_rv$D_IN;
  wire proc_m9_pff_rv$EN;

  // ports of submodule proc_m1_bram
  wire [31 : 0] proc_m1_bram$readRs, proc_m1_bram$write_d;
  wire [9 : 0] proc_m1_bram$readRq_idx, proc_m1_bram$write_idx;
  wire proc_m1_bram$EN_readRq, proc_m1_bram$EN_write;

  // ports of submodule rqs
  reg [68 : 0] rqs$D_IN;
  wire [68 : 0] rqs$D_OUT;
  wire rqs$CLR, rqs$DEQ, rqs$EMPTY_N, rqs$ENQ, rqs$FULL_N;

  // ports of submodule rss
  wire [31 : 0] rss$D_IN, rss$D_OUT;
  wire rss$CLR, rss$DEQ, rss$EMPTY_N, rss$ENQ, rss$FULL_N;

  // rule scheduling signals
  wire WILL_FIRE_RL_proc_m10_instFetchRq,
       WILL_FIRE_RL_proc_m10_instFetchRs,
       WILL_FIRE_RL_proc_m10_instFetchRsIgnore,
       WILL_FIRE_RL_proc_m10_modifyPc,
       WILL_FIRE_RL_proc_m10_pgmInitRq,
       WILL_FIRE_RL_proc_m10_pgmInitRqEnd,
       WILL_FIRE_RL_proc_m10_pgmInitRs,
       WILL_FIRE_RL_proc_m10_pgmInitRsEnd,
       WILL_FIRE_RL_proc_m11_decodeLd,
       WILL_FIRE_RL_proc_m11_decodeNm,
       WILL_FIRE_RL_proc_m11_decodeSt,
       WILL_FIRE_RL_proc_m12_execBypass,
       WILL_FIRE_RL_proc_m12_execNm,
       WILL_FIRE_RL_proc_m13_repLd,
       WILL_FIRE_RL_proc_m13_repLdZ,
       WILL_FIRE_RL_proc_m13_repSt,
       WILL_FIRE_RL_proc_m13_reqLd,
       WILL_FIRE_RL_proc_m13_reqSt,
       WILL_FIRE_RL_proc_m13_wbNm,
       WILL_FIRE_RL_proc_m13_wbNmZ,
       WILL_FIRE_RL_proc_m13_wrongEpoch;

  // inputs to muxes for submodule ports
  wire [1023 : 0] MUX_proc_m4_rf$write_1__VAL_1,
		  MUX_proc_m4_rf$write_1__VAL_2;
  wire [196 : 0] MUX_proc_m9_pff_rv$port1__write_1__VAL_1,
		 MUX_proc_m9_pff_rv$port1__write_1__VAL_2;
  wire [164 : 0] MUX_proc_m6_pff_rv$port1__write_1__VAL_1,
		 MUX_proc_m6_pff_rv$port1__write_1__VAL_2,
		 MUX_proc_m6_pff_rv$port1__write_1__VAL_3;
  wire [68 : 0] MUX_rqs$enq_1__VAL_1,
		MUX_rqs$enq_1__VAL_2,
		MUX_rqs$enq_1__VAL_3;
  wire [31 : 0] MUX_proc_m5_sbFlags$write_1__VAL_1,
		MUX_proc_m5_sbFlags$write_1__VAL_3,
		MUX_proc_m5_sbFlags$write_1__VAL_4,
		MUX_proc_m5_sbFlags$write_1__VAL_5;
  wire [24 : 0] MUX_proc_m7_pff_rv$port0__write_1__VAL_1,
		MUX_proc_m7_pff_rv$port0__write_1__VAL_2;
  wire [9 : 0] MUX_proc_m10_pinitRqOfs$write_1__VAL_1,
	       MUX_proc_m10_pinitRsOfs$write_1__VAL_1;
  wire MUX_proc_m13_stall$write_1__SEL_2,
       MUX_proc_m1_readRq$write_1__SEL_1,
       MUX_proc_m5_sbFlags$write_1__SEL_1,
       MUX_proc_m5_sbFlags$write_1__SEL_3,
       MUX_proc_m7_pff_rv$port0__write_1__PSEL_1,
       MUX_proc_m7_pff_rv$port0__write_1__PSEL_2,
       MUX_proc_m7_pff_rv$port0__write_1__SEL_1,
       MUX_proc_m8_eEpoch$write_1__SEL_1,
       MUX_rqs$enq_1__SEL_1;

  // remaining internal signals
  reg [31 : 0] CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q4,
	       CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q5,
	       CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q6,
	       CASE_proc_m6_pff_rv_BITS_56_TO_50_0x0_CASE_pro_ETC__q7,
	       SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265,
	       x_6__h48433,
	       x_9__h57090,
	       x__h44170,
	       x__h62644,
	       x__h76086,
	       y__h62779,
	       y__h76221;
  reg [11 : 0] IF_proc_m13_stalled_23_BITS_39_TO_37_34_EQ_0x0_ETC___d944,
	       IF_proc_m9_pff_rv_port0__read__83_BITS_71_TO_6_ETC___d1054,
	       x_13__h75921,
	       x_15__h62477;
  reg [9 : 0] x_6__h34631;
  reg [6 : 0] CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbTags_ETC__q11,
	      CASE_proc_m7_pff_rvport1__read_BITS_16_TO_14__ETC__q14;
  reg [1 : 0] x_4__h35126;
  reg CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbVali_ETC__q10,
      CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12,
      CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13,
      SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213,
      SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354;
  wire [959 : 0] IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d822;
  wire [895 : 0] IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d817;
  wire [831 : 0] IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d812;
  wire [767 : 0] IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d807;
  wire [703 : 0] IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d802;
  wire [639 : 0] IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d797;
  wire [575 : 0] IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d792;
  wire [511 : 0] IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d787;
  wire [447 : 0] IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d782;
  wire [383 : 0] IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d777;
  wire [319 : 0] IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d772;
  wire [255 : 0] IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d767;
  wire [191 : 0] IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d762;
  wire [127 : 0] IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d757;
  wire [31 : 0] proc_m6_pff_rv_BITS_120_TO_89__q3,
		x_9__h36794,
		x__h28916,
		x__h36894,
		x__h42154,
		x__h49213,
		y__h49354;
  wire [15 : 0] rssD_OUT_BITS_15_TO_0__q9;
  wire [11 : 0] proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_0x4___d928,
		proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_proc_ETC___d927,
		proc_m3_pff_rv_BITS_56_TO_45__q1,
		proc_m6_pff_rv_BITS_56_TO_45__q2,
		proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1034,
		proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1035,
		x_5__h34653,
		x__h42204,
		x__h49264,
		y__h62528,
		y__h62891,
		y__h75970,
		y__h76333;
  wire [9 : 0] v__h34530, x_6__h34648, x__h28884, x__h29980;
  wire [7 : 0] rssD_OUT_BITS_7_TO_0__q8;
  wire [4 : 0] x_5__h44387;
  wire NOT_IF_proc_m13_stalled_23_BITS_31_TO_25_06_EQ_ETC___d950,
       NOT_IF_proc_m9_pff_rv_port0__read__83_BITS_63__ETC___d1060,
       NOT_SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m_ETC___d386,
       NOT_proc_m7_pff_rv_port0__read__73_BIT_24_74_7_ETC___d359,
       SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d1028,
       SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d1040,
       SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d1045,
       SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d921,
       SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d931,
       SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d935,
       proc_m3_pff_rv_port0__read__76_BIT_57_77_AND_N_ETC___d226,
       proc_m7_pff_rv_port1__read__4_BITS_11_TO_2_6_E_ETC___d59,
       proc_m9_pff_rv_port0__read__83_BIT_32_85_EQ_pr_ETC___d587;

  // actionvalue method obtain_rq_get
  assign obtain_rq_get = rqs$D_OUT ;
  assign RDY_obtain_rq_get = rqs$EMPTY_N ;

  // action method send_rs_put
  assign RDY_send_rs_put = rss$FULL_N ;

  // submodule proc_m1_bram
  mkBramInst proc_m1_bram(.CLK(CLK),
			  .RST_N(RST_N),
			  .readRq_idx(proc_m1_bram$readRq_idx),
			  .write_d(proc_m1_bram$write_d),
			  .write_idx(proc_m1_bram$write_idx),
			  .EN_readRq(proc_m1_bram$EN_readRq),
			  .EN_write(proc_m1_bram$EN_write),
			  .RDY_readRq(),
			  .readRs(proc_m1_bram$readRs),
			  .RDY_readRs(),
			  .RDY_write());

  // submodule rqs
  FIFO2 #(.width(32'd69), .guarded(32'd1)) rqs(.RST(RST_N),
					       .CLK(CLK),
					       .D_IN(rqs$D_IN),
					       .ENQ(rqs$ENQ),
					       .DEQ(rqs$DEQ),
					       .CLR(rqs$CLR),
					       .D_OUT(rqs$D_OUT),
					       .FULL_N(rqs$FULL_N),
					       .EMPTY_N(rqs$EMPTY_N));

  // submodule rss
  FIFO2 #(.width(32'd32), .guarded(32'd1)) rss(.RST(RST_N),
					       .CLK(CLK),
					       .D_IN(rss$D_IN),
					       .ENQ(rss$ENQ),
					       .DEQ(rss$DEQ),
					       .CLR(rss$CLR),
					       .D_OUT(rss$D_OUT),
					       .FULL_N(rss$FULL_N),
					       .EMPTY_N(rss$EMPTY_N));

  // rule RL_proc_m10_pgmInitRq
  assign WILL_FIRE_RL_proc_m10_pgmInitRq =
	     !proc_m10_pinit && !proc_m10_pinitRq && x__h28884 != 10'h0 &&
	     rqs$FULL_N ;

  // rule RL_proc_m10_pgmInitRqEnd
  assign WILL_FIRE_RL_proc_m10_pgmInitRqEnd =
	     !proc_m10_pinit && !proc_m10_pinitRq && x__h28884 == 10'h0 &&
	     rqs$FULL_N ;

  // rule RL_proc_m10_pgmInitRs
  assign WILL_FIRE_RL_proc_m10_pgmInitRs =
	     !proc_m10_pinit && x__h29980 != 10'h0 && !proc_m1_readRq &&
	     rss$EMPTY_N ;

  // rule RL_proc_m10_pgmInitRsEnd
  assign WILL_FIRE_RL_proc_m10_pgmInitRsEnd =
	     !proc_m10_pinit && !proc_m1_readRq && x__h29980 == 10'h0 &&
	     rss$EMPTY_N ;

  // rule RL_proc_m10_instFetchRq
  assign WILL_FIRE_RL_proc_m10_instFetchRq =
	     !proc_m1_readRq && proc_m10_pinit ;

  // rule RL_proc_m10_instFetchRsIgnore
  assign WILL_FIRE_RL_proc_m10_instFetchRsIgnore =
	     proc_m10_pinit && proc_m1_readRq && proc_m10_pcUpdated ;

  // rule RL_proc_m13_wrongEpoch
  assign WILL_FIRE_RL_proc_m13_wrongEpoch =
	     !proc_m13_stall && proc_m9_pff_rv[196] &&
	     !proc_m9_pff_rv_port0__read__83_BIT_32_85_EQ_pr_ETC___d587 ;

  // rule RL_proc_m13_reqLd
  assign WILL_FIRE_RL_proc_m13_reqLd =
	     !proc_m13_stall && proc_m9_pff_rv[196] &&
	     proc_m9_pff_rv_port0__read__83_BIT_32_85_EQ_pr_ETC___d587 &&
	     proc_m9_pff_rv[195:194] == 2'h0 &&
	     rqs$FULL_N &&
	     !WILL_FIRE_RL_proc_m10_pgmInitRqEnd &&
	     !WILL_FIRE_RL_proc_m10_pgmInitRq ;

  // rule RL_proc_m13_reqSt
  assign WILL_FIRE_RL_proc_m13_reqSt =
	     !proc_m13_stall && proc_m9_pff_rv[196] &&
	     proc_m9_pff_rv_port0__read__83_BIT_32_85_EQ_pr_ETC___d587 &&
	     proc_m9_pff_rv[195:194] == 2'h1 &&
	     rqs$FULL_N &&
	     !WILL_FIRE_RL_proc_m10_pgmInitRqEnd &&
	     !WILL_FIRE_RL_proc_m10_pgmInitRq ;

  // rule RL_proc_m13_wbNm
  assign WILL_FIRE_RL_proc_m13_wbNm =
	     !proc_m13_stall && proc_m9_pff_rv[196] &&
	     proc_m9_pff_rv[193:189] != 5'd0 &&
	     proc_m9_pff_rv_port0__read__83_BIT_32_85_EQ_pr_ETC___d587 &&
	     proc_m9_pff_rv[195:194] == 2'h3 &&
	     !proc_m7_pff_rv[24] ;

  // rule RL_proc_m13_wbNmZ
  assign WILL_FIRE_RL_proc_m13_wbNmZ =
	     !proc_m13_stall && proc_m9_pff_rv[196] &&
	     proc_m9_pff_rv_port0__read__83_BIT_32_85_EQ_pr_ETC___d587 &&
	     proc_m9_pff_rv[195:194] == 2'h3 &&
	     proc_m9_pff_rv[193:189] == 5'd0 &&
	     !proc_m7_pff_rv[24] ;

  // rule RL_proc_m12_execNm
  assign WILL_FIRE_RL_proc_m12_execNm =
	     proc_m6_pff_rv[164] && proc_m6_pff_rv[163:162] == 2'h3 &&
	     !proc_m9_pff_rv$port1__read[196] ;

  // rule RL_proc_m12_execBypass
  assign WILL_FIRE_RL_proc_m12_execBypass =
	     proc_m6_pff_rv[164] && proc_m6_pff_rv[163:162] != 2'h3 &&
	     !proc_m9_pff_rv$port1__read[196] &&
	     !WILL_FIRE_RL_proc_m13_wrongEpoch ;

  // rule RL_proc_m11_decodeLd
  assign WILL_FIRE_RL_proc_m11_decodeLd =
	     !proc_m7_pff_rv[24] &&
	     proc_m3_pff_rv_port0__read__76_BIT_57_77_AND_N_ETC___d226 &&
	     !WILL_FIRE_RL_proc_m13_wbNmZ &&
	     !WILL_FIRE_RL_proc_m13_wbNm &&
	     !WILL_FIRE_RL_proc_m13_repLdZ &&
	     !WILL_FIRE_RL_proc_m13_repLd &&
	     !WILL_FIRE_RL_proc_m13_wrongEpoch ;

  // rule RL_proc_m11_decodeSt
  assign WILL_FIRE_RL_proc_m11_decodeSt =
	     proc_m3_pff_rv[57] &&
	     NOT_proc_m7_pff_rv_port0__read__73_BIT_24_74_7_ETC___d359 &&
	     !WILL_FIRE_RL_proc_m12_execNm &&
	     !WILL_FIRE_RL_proc_m13_wbNmZ &&
	     !WILL_FIRE_RL_proc_m13_wbNm &&
	     !WILL_FIRE_RL_proc_m13_wrongEpoch ;

  // rule RL_proc_m11_decodeNm
  assign WILL_FIRE_RL_proc_m11_decodeNm =
	     proc_m3_pff_rv[57] && !proc_m7_pff_rv[24] &&
	     NOT_SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m_ETC___d386 &&
	     !WILL_FIRE_RL_proc_m13_wbNmZ &&
	     !WILL_FIRE_RL_proc_m13_wbNm &&
	     !WILL_FIRE_RL_proc_m13_repLdZ &&
	     !WILL_FIRE_RL_proc_m13_repLd &&
	     !WILL_FIRE_RL_proc_m13_wrongEpoch ;

  // rule RL_proc_m10_instFetchRs
  assign WILL_FIRE_RL_proc_m10_instFetchRs =
	     !proc_m10_pcUpdated && proc_m10_pinit && proc_m1_readRq &&
	     !proc_m3_pff_rv$port1__read[57] ;

  // rule RL_proc_m13_repLd
  assign WILL_FIRE_RL_proc_m13_repLd =
	     proc_m13_stalled[161:157] != 5'h0 &&
	     proc_m13_stalled[163:162] == 2'h0 &&
	     rss$EMPTY_N &&
	     proc_m13_stall &&
	     !proc_m7_pff_rv[24] &&
	     !WILL_FIRE_RL_proc_m10_pgmInitRsEnd &&
	     !WILL_FIRE_RL_proc_m10_pgmInitRs ;

  // rule RL_proc_m13_repLdZ
  assign WILL_FIRE_RL_proc_m13_repLdZ =
	     proc_m13_stalled[163:162] == 2'h0 &&
	     proc_m13_stalled[161:157] == 5'h0 &&
	     rss$EMPTY_N &&
	     proc_m13_stall &&
	     !proc_m7_pff_rv[24] &&
	     !WILL_FIRE_RL_proc_m10_pgmInitRsEnd &&
	     !WILL_FIRE_RL_proc_m10_pgmInitRs ;

  // rule RL_proc_m13_repSt
  assign WILL_FIRE_RL_proc_m13_repSt =
	     proc_m13_stalled[163:162] == 2'h1 && rss$EMPTY_N &&
	     proc_m13_stall &&
	     !proc_m7_pff_rv[24] &&
	     !WILL_FIRE_RL_proc_m10_pgmInitRsEnd &&
	     !WILL_FIRE_RL_proc_m10_pgmInitRs ;

  // rule RL_proc_m10_modifyPc
  assign WILL_FIRE_RL_proc_m10_modifyPc =
	     proc_m7_pff_rv$port1__read[24] && proc_m10_pinit ;

  // inputs to muxes for submodule ports
  assign MUX_proc_m13_stall$write_1__SEL_2 =
	     WILL_FIRE_RL_proc_m13_reqSt || WILL_FIRE_RL_proc_m13_reqLd ;
  assign MUX_proc_m1_readRq$write_1__SEL_1 =
	     WILL_FIRE_RL_proc_m10_instFetchRsIgnore ||
	     WILL_FIRE_RL_proc_m10_instFetchRs ;
  assign MUX_proc_m5_sbFlags$write_1__SEL_1 =
	     WILL_FIRE_RL_proc_m13_wrongEpoch &&
	     (proc_m9_pff_rv[195:194] == 2'h0 ||
	      proc_m9_pff_rv[195:194] == 2'h3) ;
  assign MUX_proc_m5_sbFlags$write_1__SEL_3 =
	     WILL_FIRE_RL_proc_m13_repLdZ || WILL_FIRE_RL_proc_m13_repLd ;
  assign MUX_proc_m7_pff_rv$port0__write_1__PSEL_1 =
	     WILL_FIRE_RL_proc_m13_repSt || WILL_FIRE_RL_proc_m13_repLdZ ||
	     WILL_FIRE_RL_proc_m13_repLd ;
  assign MUX_proc_m7_pff_rv$port0__write_1__SEL_1 =
	     MUX_proc_m7_pff_rv$port0__write_1__PSEL_1 &&
	     NOT_IF_proc_m13_stalled_23_BITS_31_TO_25_06_EQ_ETC___d950 ;
  assign MUX_proc_m7_pff_rv$port0__write_1__PSEL_2 =
	     WILL_FIRE_RL_proc_m13_wbNmZ || WILL_FIRE_RL_proc_m13_wbNm ;
  assign MUX_proc_m8_eEpoch$write_1__SEL_1 =
	     MUX_proc_m7_pff_rv$port0__write_1__PSEL_1 &&
	     NOT_IF_proc_m13_stalled_23_BITS_31_TO_25_06_EQ_ETC___d950 ;
  assign MUX_rqs$enq_1__SEL_1 =
	     WILL_FIRE_RL_proc_m10_pgmInitRqEnd ||
	     WILL_FIRE_RL_proc_m10_pgmInitRq ;
  assign MUX_proc_m10_pinitRqOfs$write_1__VAL_1 =
	     proc_m10_pinitRqOfs + 10'h001 ;
  assign MUX_proc_m10_pinitRsOfs$write_1__VAL_1 =
	     proc_m10_pinitRsOfs + 10'h001 ;
  assign MUX_proc_m4_rf$write_1__VAL_1 =
	     { IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d822,
	       (proc_m13_stalled[161:157] == 5'd1) ?
		 x_9__h57090 :
		 proc_m4_rf[63:32],
	       proc_m4_rf[31:0] } ;
  assign MUX_proc_m4_rf$write_1__VAL_2 =
	     { (proc_m9_pff_rv[193:189] == 5'd31) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[1023:992],
	       (proc_m9_pff_rv[193:189] == 5'd30) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[991:960],
	       (proc_m9_pff_rv[193:189] == 5'd29) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[959:928],
	       (proc_m9_pff_rv[193:189] == 5'd28) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[927:896],
	       (proc_m9_pff_rv[193:189] == 5'd27) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[895:864],
	       (proc_m9_pff_rv[193:189] == 5'd26) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[863:832],
	       (proc_m9_pff_rv[193:189] == 5'd25) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[831:800],
	       (proc_m9_pff_rv[193:189] == 5'd24) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[799:768],
	       (proc_m9_pff_rv[193:189] == 5'd23) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[767:736],
	       (proc_m9_pff_rv[193:189] == 5'd22) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[735:704],
	       (proc_m9_pff_rv[193:189] == 5'd21) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[703:672],
	       (proc_m9_pff_rv[193:189] == 5'd20) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[671:640],
	       (proc_m9_pff_rv[193:189] == 5'd19) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[639:608],
	       (proc_m9_pff_rv[193:189] == 5'd18) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[607:576],
	       (proc_m9_pff_rv[193:189] == 5'd17) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[575:544],
	       (proc_m9_pff_rv[193:189] == 5'd16) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[543:512],
	       (proc_m9_pff_rv[193:189] == 5'd15) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[511:480],
	       (proc_m9_pff_rv[193:189] == 5'd14) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[479:448],
	       (proc_m9_pff_rv[193:189] == 5'd13) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[447:416],
	       (proc_m9_pff_rv[193:189] == 5'd12) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[415:384],
	       (proc_m9_pff_rv[193:189] == 5'd11) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[383:352],
	       (proc_m9_pff_rv[193:189] == 5'd10) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[351:320],
	       (proc_m9_pff_rv[193:189] == 5'd9) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[319:288],
	       (proc_m9_pff_rv[193:189] == 5'd8) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[287:256],
	       (proc_m9_pff_rv[193:189] == 5'd7) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[255:224],
	       (proc_m9_pff_rv[193:189] == 5'd6) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[223:192],
	       (proc_m9_pff_rv[193:189] == 5'd5) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[191:160],
	       (proc_m9_pff_rv[193:189] == 5'd4) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[159:128],
	       (proc_m9_pff_rv[193:189] == 5'd3) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[127:96],
	       (proc_m9_pff_rv[193:189] == 5'd2) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[95:64],
	       (proc_m9_pff_rv[193:189] == 5'd1) ?
		 proc_m9_pff_rv[31:0] :
		 proc_m4_rf[63:32],
	       proc_m4_rf[31:0] } ;
  assign MUX_proc_m5_sbFlags$write_1__VAL_1 =
	     { proc_m9_pff_rv[193:189] != 5'd31 && proc_m5_sbFlags[31],
	       proc_m9_pff_rv[193:189] != 5'd30 && proc_m5_sbFlags[30],
	       proc_m9_pff_rv[193:189] != 5'd29 && proc_m5_sbFlags[29],
	       proc_m9_pff_rv[193:189] != 5'd28 && proc_m5_sbFlags[28],
	       proc_m9_pff_rv[193:189] != 5'd27 && proc_m5_sbFlags[27],
	       proc_m9_pff_rv[193:189] != 5'd26 && proc_m5_sbFlags[26],
	       proc_m9_pff_rv[193:189] != 5'd25 && proc_m5_sbFlags[25],
	       proc_m9_pff_rv[193:189] != 5'd24 && proc_m5_sbFlags[24],
	       proc_m9_pff_rv[193:189] != 5'd23 && proc_m5_sbFlags[23],
	       proc_m9_pff_rv[193:189] != 5'd22 && proc_m5_sbFlags[22],
	       proc_m9_pff_rv[193:189] != 5'd21 && proc_m5_sbFlags[21],
	       proc_m9_pff_rv[193:189] != 5'd20 && proc_m5_sbFlags[20],
	       proc_m9_pff_rv[193:189] != 5'd19 && proc_m5_sbFlags[19],
	       proc_m9_pff_rv[193:189] != 5'd18 && proc_m5_sbFlags[18],
	       proc_m9_pff_rv[193:189] != 5'd17 && proc_m5_sbFlags[17],
	       proc_m9_pff_rv[193:189] != 5'd16 && proc_m5_sbFlags[16],
	       proc_m9_pff_rv[193:189] != 5'd15 && proc_m5_sbFlags[15],
	       proc_m9_pff_rv[193:189] != 5'd14 && proc_m5_sbFlags[14],
	       proc_m9_pff_rv[193:189] != 5'd13 && proc_m5_sbFlags[13],
	       proc_m9_pff_rv[193:189] != 5'd12 && proc_m5_sbFlags[12],
	       proc_m9_pff_rv[193:189] != 5'd11 && proc_m5_sbFlags[11],
	       proc_m9_pff_rv[193:189] != 5'd10 && proc_m5_sbFlags[10],
	       proc_m9_pff_rv[193:189] != 5'd9 && proc_m5_sbFlags[9],
	       proc_m9_pff_rv[193:189] != 5'd8 && proc_m5_sbFlags[8],
	       proc_m9_pff_rv[193:189] != 5'd7 && proc_m5_sbFlags[7],
	       proc_m9_pff_rv[193:189] != 5'd6 && proc_m5_sbFlags[6],
	       proc_m9_pff_rv[193:189] != 5'd5 && proc_m5_sbFlags[5],
	       proc_m9_pff_rv[193:189] != 5'd4 && proc_m5_sbFlags[4],
	       proc_m9_pff_rv[193:189] != 5'd3 && proc_m5_sbFlags[3],
	       proc_m9_pff_rv[193:189] != 5'd2 && proc_m5_sbFlags[2],
	       proc_m9_pff_rv[193:189] != 5'd1 && proc_m5_sbFlags[1],
	       proc_m9_pff_rv[193:189] != 5'd0 && proc_m5_sbFlags[0] } ;
  assign MUX_proc_m5_sbFlags$write_1__VAL_3 =
	     { proc_m13_stalled[161:157] != 5'd31 && proc_m5_sbFlags[31],
	       proc_m13_stalled[161:157] != 5'd30 && proc_m5_sbFlags[30],
	       proc_m13_stalled[161:157] != 5'd29 && proc_m5_sbFlags[29],
	       proc_m13_stalled[161:157] != 5'd28 && proc_m5_sbFlags[28],
	       proc_m13_stalled[161:157] != 5'd27 && proc_m5_sbFlags[27],
	       proc_m13_stalled[161:157] != 5'd26 && proc_m5_sbFlags[26],
	       proc_m13_stalled[161:157] != 5'd25 && proc_m5_sbFlags[25],
	       proc_m13_stalled[161:157] != 5'd24 && proc_m5_sbFlags[24],
	       proc_m13_stalled[161:157] != 5'd23 && proc_m5_sbFlags[23],
	       proc_m13_stalled[161:157] != 5'd22 && proc_m5_sbFlags[22],
	       proc_m13_stalled[161:157] != 5'd21 && proc_m5_sbFlags[21],
	       proc_m13_stalled[161:157] != 5'd20 && proc_m5_sbFlags[20],
	       proc_m13_stalled[161:157] != 5'd19 && proc_m5_sbFlags[19],
	       proc_m13_stalled[161:157] != 5'd18 && proc_m5_sbFlags[18],
	       proc_m13_stalled[161:157] != 5'd17 && proc_m5_sbFlags[17],
	       proc_m13_stalled[161:157] != 5'd16 && proc_m5_sbFlags[16],
	       proc_m13_stalled[161:157] != 5'd15 && proc_m5_sbFlags[15],
	       proc_m13_stalled[161:157] != 5'd14 && proc_m5_sbFlags[14],
	       proc_m13_stalled[161:157] != 5'd13 && proc_m5_sbFlags[13],
	       proc_m13_stalled[161:157] != 5'd12 && proc_m5_sbFlags[12],
	       proc_m13_stalled[161:157] != 5'd11 && proc_m5_sbFlags[11],
	       proc_m13_stalled[161:157] != 5'd10 && proc_m5_sbFlags[10],
	       proc_m13_stalled[161:157] != 5'd9 && proc_m5_sbFlags[9],
	       proc_m13_stalled[161:157] != 5'd8 && proc_m5_sbFlags[8],
	       proc_m13_stalled[161:157] != 5'd7 && proc_m5_sbFlags[7],
	       proc_m13_stalled[161:157] != 5'd6 && proc_m5_sbFlags[6],
	       proc_m13_stalled[161:157] != 5'd5 && proc_m5_sbFlags[5],
	       proc_m13_stalled[161:157] != 5'd4 && proc_m5_sbFlags[4],
	       proc_m13_stalled[161:157] != 5'd3 && proc_m5_sbFlags[3],
	       proc_m13_stalled[161:157] != 5'd2 && proc_m5_sbFlags[2],
	       proc_m13_stalled[161:157] != 5'd1 && proc_m5_sbFlags[1],
	       proc_m13_stalled[161:157] != 5'h0 && proc_m5_sbFlags[0] } ;
  assign MUX_proc_m5_sbFlags$write_1__VAL_4 =
	     { proc_m3_pff_rv[36:32] == 5'd31 || proc_m5_sbFlags[31],
	       proc_m3_pff_rv[36:32] == 5'd30 || proc_m5_sbFlags[30],
	       proc_m3_pff_rv[36:32] == 5'd29 || proc_m5_sbFlags[29],
	       proc_m3_pff_rv[36:32] == 5'd28 || proc_m5_sbFlags[28],
	       proc_m3_pff_rv[36:32] == 5'd27 || proc_m5_sbFlags[27],
	       proc_m3_pff_rv[36:32] == 5'd26 || proc_m5_sbFlags[26],
	       proc_m3_pff_rv[36:32] == 5'd25 || proc_m5_sbFlags[25],
	       proc_m3_pff_rv[36:32] == 5'd24 || proc_m5_sbFlags[24],
	       proc_m3_pff_rv[36:32] == 5'd23 || proc_m5_sbFlags[23],
	       proc_m3_pff_rv[36:32] == 5'd22 || proc_m5_sbFlags[22],
	       proc_m3_pff_rv[36:32] == 5'd21 || proc_m5_sbFlags[21],
	       proc_m3_pff_rv[36:32] == 5'd20 || proc_m5_sbFlags[20],
	       proc_m3_pff_rv[36:32] == 5'd19 || proc_m5_sbFlags[19],
	       proc_m3_pff_rv[36:32] == 5'd18 || proc_m5_sbFlags[18],
	       proc_m3_pff_rv[36:32] == 5'd17 || proc_m5_sbFlags[17],
	       proc_m3_pff_rv[36:32] == 5'd16 || proc_m5_sbFlags[16],
	       proc_m3_pff_rv[36:32] == 5'd15 || proc_m5_sbFlags[15],
	       proc_m3_pff_rv[36:32] == 5'd14 || proc_m5_sbFlags[14],
	       proc_m3_pff_rv[36:32] == 5'd13 || proc_m5_sbFlags[13],
	       proc_m3_pff_rv[36:32] == 5'd12 || proc_m5_sbFlags[12],
	       proc_m3_pff_rv[36:32] == 5'd11 || proc_m5_sbFlags[11],
	       proc_m3_pff_rv[36:32] == 5'd10 || proc_m5_sbFlags[10],
	       proc_m3_pff_rv[36:32] == 5'd9 || proc_m5_sbFlags[9],
	       proc_m3_pff_rv[36:32] == 5'd8 || proc_m5_sbFlags[8],
	       proc_m3_pff_rv[36:32] == 5'd7 || proc_m5_sbFlags[7],
	       proc_m3_pff_rv[36:32] == 5'd6 || proc_m5_sbFlags[6],
	       proc_m3_pff_rv[36:32] == 5'd5 || proc_m5_sbFlags[5],
	       proc_m3_pff_rv[36:32] == 5'd4 || proc_m5_sbFlags[4],
	       proc_m3_pff_rv[36:32] == 5'd3 || proc_m5_sbFlags[3],
	       proc_m3_pff_rv[36:32] == 5'd2 || proc_m5_sbFlags[2],
	       proc_m3_pff_rv[36:32] == 5'd1 || proc_m5_sbFlags[1],
	       proc_m3_pff_rv[36:32] == 5'd0 || proc_m5_sbFlags[0] } ;
  assign MUX_proc_m5_sbFlags$write_1__VAL_5 =
	     { x_5__h44387 == 5'd31 || proc_m5_sbFlags[31],
	       x_5__h44387 == 5'd30 || proc_m5_sbFlags[30],
	       x_5__h44387 == 5'd29 || proc_m5_sbFlags[29],
	       x_5__h44387 == 5'd28 || proc_m5_sbFlags[28],
	       x_5__h44387 == 5'd27 || proc_m5_sbFlags[27],
	       x_5__h44387 == 5'd26 || proc_m5_sbFlags[26],
	       x_5__h44387 == 5'd25 || proc_m5_sbFlags[25],
	       x_5__h44387 == 5'd24 || proc_m5_sbFlags[24],
	       x_5__h44387 == 5'd23 || proc_m5_sbFlags[23],
	       x_5__h44387 == 5'd22 || proc_m5_sbFlags[22],
	       x_5__h44387 == 5'd21 || proc_m5_sbFlags[21],
	       x_5__h44387 == 5'd20 || proc_m5_sbFlags[20],
	       x_5__h44387 == 5'd19 || proc_m5_sbFlags[19],
	       x_5__h44387 == 5'd18 || proc_m5_sbFlags[18],
	       x_5__h44387 == 5'd17 || proc_m5_sbFlags[17],
	       x_5__h44387 == 5'd16 || proc_m5_sbFlags[16],
	       x_5__h44387 == 5'd15 || proc_m5_sbFlags[15],
	       x_5__h44387 == 5'd14 || proc_m5_sbFlags[14],
	       x_5__h44387 == 5'd13 || proc_m5_sbFlags[13],
	       x_5__h44387 == 5'd12 || proc_m5_sbFlags[12],
	       x_5__h44387 == 5'd11 || proc_m5_sbFlags[11],
	       x_5__h44387 == 5'd10 || proc_m5_sbFlags[10],
	       x_5__h44387 == 5'd9 || proc_m5_sbFlags[9],
	       x_5__h44387 == 5'd8 || proc_m5_sbFlags[8],
	       x_5__h44387 == 5'd7 || proc_m5_sbFlags[7],
	       x_5__h44387 == 5'd6 || proc_m5_sbFlags[6],
	       x_5__h44387 == 5'd5 || proc_m5_sbFlags[5],
	       x_5__h44387 == 5'd4 || proc_m5_sbFlags[4],
	       x_5__h44387 == 5'd3 || proc_m5_sbFlags[3],
	       x_5__h44387 == 5'd2 || proc_m5_sbFlags[2],
	       x_5__h44387 == 5'd1 || proc_m5_sbFlags[1],
	       x_5__h44387 == 5'd0 || proc_m5_sbFlags[0] } ;
  assign MUX_proc_m6_pff_rv$port1__write_1__VAL_1 =
	     { 1'd1,
	       x_4__h35126,
	       proc_m3_pff_rv[36:32],
	       x__h36894,
	       68'd0,
	       proc_m3_pff_rv[56:0] } ;
  assign MUX_proc_m6_pff_rv$port1__write_1__VAL_2 =
	     { 1'd1,
	       x_4__h35126,
	       5'h0,
	       x__h42154,
	       proc_m3_pff_rv[39:37] != 3'h0 && proc_m3_pff_rv[39:37] != 3'h1,
	       proc_m3_pff_rv[39:37] != 3'h0 && proc_m3_pff_rv[39:37] != 3'h1,
	       proc_m3_pff_rv[39:37] != 3'h0,
	       1'd1,
	       x__h44170,
	       32'h0,
	       proc_m3_pff_rv[56:0] } ;
  assign MUX_proc_m6_pff_rv$port1__write_1__VAL_3 =
	     { 1'd1,
	       x_4__h35126,
	       x_5__h44387,
	       36'd0,
	       SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265,
	       x__h44170,
	       proc_m3_pff_rv[56:0] } ;
  assign MUX_proc_m7_pff_rv$port0__write_1__VAL_1 =
	     { 1'd1, proc_m13_stalled[24:13], x_15__h62477 } ;
  assign MUX_proc_m7_pff_rv$port0__write_1__VAL_2 =
	     { 1'd1, proc_m9_pff_rv[56:45], x_13__h75921 } ;
  assign MUX_proc_m9_pff_rv$port1__write_1__VAL_1 =
	     { 1'd1, proc_m6_pff_rv[163:0], x_6__h48433 } ;
  assign MUX_proc_m9_pff_rv$port1__write_1__VAL_2 =
	     { 1'd1, proc_m6_pff_rv[163:0], 32'h0 } ;
  assign MUX_rqs$enq_1__VAL_1 = { x__h28916, 37'd0 } ;
  assign MUX_rqs$enq_1__VAL_2 = { proc_m9_pff_rv[188:157], 37'd0 } ;
  assign MUX_rqs$enq_1__VAL_3 =
	     { proc_m9_pff_rv[188:157], 1'd1, proc_m9_pff_rv[156:121] } ;

  // inlined wires
  assign proc_m3_pff_rv$EN_port0__write =
	     WILL_FIRE_RL_proc_m11_decodeNm ||
	     WILL_FIRE_RL_proc_m11_decodeSt ||
	     WILL_FIRE_RL_proc_m11_decodeLd ;
  assign proc_m3_pff_rv$port1__read =
	     proc_m3_pff_rv$EN_port0__write ?
	       58'h0AAAAAAAAAAAAAA :
	       proc_m3_pff_rv ;
  assign proc_m3_pff_rv$port1__write_1 =
	     { 1'd1,
	       proc_m1_bram$readRs,
	       proc_m10_pc,
	       x_5__h34653,
	       proc_m10_fEpoch } ;
  assign proc_m3_pff_rv$port2__read =
	     WILL_FIRE_RL_proc_m10_instFetchRs ?
	       proc_m3_pff_rv$port1__write_1 :
	       proc_m3_pff_rv$port1__read ;
  assign proc_m3_pff_rv$port3__read =
	     WILL_FIRE_RL_proc_m10_modifyPc ?
	       58'h0AAAAAAAAAAAAAA :
	       proc_m3_pff_rv$port2__read ;
  assign proc_m6_pff_rv$EN_port0__write =
	     WILL_FIRE_RL_proc_m12_execBypass ||
	     WILL_FIRE_RL_proc_m12_execNm ;
  assign proc_m6_pff_rv$port1__read =
	     proc_m6_pff_rv$EN_port0__write ?
	       165'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA :
	       proc_m6_pff_rv ;
  assign proc_m6_pff_rv$EN_port1__write =
	     WILL_FIRE_RL_proc_m11_decodeLd ||
	     WILL_FIRE_RL_proc_m11_decodeSt ||
	     WILL_FIRE_RL_proc_m11_decodeNm ;
  always@(WILL_FIRE_RL_proc_m11_decodeLd or
	  MUX_proc_m6_pff_rv$port1__write_1__VAL_1 or
	  WILL_FIRE_RL_proc_m11_decodeSt or
	  MUX_proc_m6_pff_rv$port1__write_1__VAL_2 or
	  WILL_FIRE_RL_proc_m11_decodeNm or
	  MUX_proc_m6_pff_rv$port1__write_1__VAL_3)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_proc_m11_decodeLd:
	  proc_m6_pff_rv$port1__write_1 =
	      MUX_proc_m6_pff_rv$port1__write_1__VAL_1;
      WILL_FIRE_RL_proc_m11_decodeSt:
	  proc_m6_pff_rv$port1__write_1 =
	      MUX_proc_m6_pff_rv$port1__write_1__VAL_2;
      WILL_FIRE_RL_proc_m11_decodeNm:
	  proc_m6_pff_rv$port1__write_1 =
	      MUX_proc_m6_pff_rv$port1__write_1__VAL_3;
      default: proc_m6_pff_rv$port1__write_1 =
		   165'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign proc_m6_pff_rv$port2__read =
	     proc_m6_pff_rv$EN_port1__write ?
	       proc_m6_pff_rv$port1__write_1 :
	       proc_m6_pff_rv$port1__read ;
  assign proc_m7_pff_rv$EN_port0__write =
	     (WILL_FIRE_RL_proc_m13_repSt || WILL_FIRE_RL_proc_m13_repLdZ ||
	      WILL_FIRE_RL_proc_m13_repLd) &&
	     NOT_IF_proc_m13_stalled_23_BITS_31_TO_25_06_EQ_ETC___d950 ||
	     (WILL_FIRE_RL_proc_m13_wbNmZ || WILL_FIRE_RL_proc_m13_wbNm) &&
	     NOT_IF_proc_m9_pff_rv_port0__read__83_BITS_63__ETC___d1060 ;
  assign proc_m7_pff_rv$port0__write_1 =
	     MUX_proc_m7_pff_rv$port0__write_1__SEL_1 ?
	       MUX_proc_m7_pff_rv$port0__write_1__VAL_1 :
	       MUX_proc_m7_pff_rv$port0__write_1__VAL_2 ;
  assign proc_m7_pff_rv$port1__read =
	     proc_m7_pff_rv$EN_port0__write ?
	       proc_m7_pff_rv$port0__write_1 :
	       proc_m7_pff_rv ;
  assign proc_m7_pff_rv$port2__read =
	     WILL_FIRE_RL_proc_m10_modifyPc ?
	       25'd11184810 :
	       proc_m7_pff_rv$port1__read ;
  assign proc_m9_pff_rv$EN_port0__write =
	     WILL_FIRE_RL_proc_m13_wbNmZ || WILL_FIRE_RL_proc_m13_wbNm ||
	     WILL_FIRE_RL_proc_m13_reqSt ||
	     WILL_FIRE_RL_proc_m13_reqLd ||
	     WILL_FIRE_RL_proc_m13_wrongEpoch ;
  assign proc_m9_pff_rv$port1__read =
	     proc_m9_pff_rv$EN_port0__write ?
	       197'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA :
	       proc_m9_pff_rv ;
  assign proc_m9_pff_rv$EN_port1__write =
	     WILL_FIRE_RL_proc_m12_execNm ||
	     WILL_FIRE_RL_proc_m12_execBypass ;
  assign proc_m9_pff_rv$port1__write_1 =
	     WILL_FIRE_RL_proc_m12_execNm ?
	       MUX_proc_m9_pff_rv$port1__write_1__VAL_1 :
	       MUX_proc_m9_pff_rv$port1__write_1__VAL_2 ;
  assign proc_m9_pff_rv$port2__read =
	     proc_m9_pff_rv$EN_port1__write ?
	       proc_m9_pff_rv$port1__write_1 :
	       proc_m9_pff_rv$port1__read ;

  // register proc_m10_fEpoch
  assign proc_m10_fEpoch$D_IN = !proc_m10_fEpoch ;
  assign proc_m10_fEpoch$EN = WILL_FIRE_RL_proc_m10_modifyPc ;

  // register proc_m10_pc
  assign proc_m10_pc$D_IN =
	     WILL_FIRE_RL_proc_m10_modifyPc ?
	       proc_m7_pff_rv$port1__read[11:0] :
	       x_5__h34653 ;
  assign proc_m10_pc$EN =
	     WILL_FIRE_RL_proc_m10_instFetchRs ||
	     WILL_FIRE_RL_proc_m10_modifyPc ;

  // register proc_m10_pcUpdated
  assign proc_m10_pcUpdated$D_IN = WILL_FIRE_RL_proc_m10_modifyPc ;
  assign proc_m10_pcUpdated$EN =
	     WILL_FIRE_RL_proc_m10_instFetchRsIgnore ||
	     WILL_FIRE_RL_proc_m10_instFetchRq ||
	     WILL_FIRE_RL_proc_m10_modifyPc ;

  // register proc_m10_pinit
  assign proc_m10_pinit$D_IN = 1'd1 ;
  assign proc_m10_pinit$EN = WILL_FIRE_RL_proc_m10_pgmInitRsEnd ;

  // register proc_m10_pinitRq
  assign proc_m10_pinitRq$D_IN = 1'd1 ;
  assign proc_m10_pinitRq$EN = WILL_FIRE_RL_proc_m10_pgmInitRqEnd ;

  // register proc_m10_pinitRqOfs
  assign proc_m10_pinitRqOfs$D_IN =
	     WILL_FIRE_RL_proc_m10_pgmInitRq ?
	       MUX_proc_m10_pinitRqOfs$write_1__VAL_1 :
	       10'h0 ;
  assign proc_m10_pinitRqOfs$EN =
	     WILL_FIRE_RL_proc_m10_pgmInitRq ||
	     WILL_FIRE_RL_proc_m10_pgmInitRqEnd ;

  // register proc_m10_pinitRsOfs
  assign proc_m10_pinitRsOfs$D_IN =
	     WILL_FIRE_RL_proc_m10_pgmInitRs ?
	       MUX_proc_m10_pinitRsOfs$write_1__VAL_1 :
	       10'h0 ;
  assign proc_m10_pinitRsOfs$EN =
	     WILL_FIRE_RL_proc_m10_pgmInitRs ||
	     WILL_FIRE_RL_proc_m10_pgmInitRsEnd ;

  // register proc_m13_lastPc
  assign proc_m13_lastPc$D_IN =
	     MUX_proc_m7_pff_rv$port0__write_1__PSEL_1 ?
	       proc_m13_stalled[24:13] :
	       proc_m9_pff_rv[56:45] ;
  assign proc_m13_lastPc$EN =
	     WILL_FIRE_RL_proc_m13_repSt || WILL_FIRE_RL_proc_m13_repLdZ ||
	     WILL_FIRE_RL_proc_m13_repLd ||
	     WILL_FIRE_RL_proc_m13_wbNmZ ||
	     WILL_FIRE_RL_proc_m13_wbNm ;

  // register proc_m13_stall
  assign proc_m13_stall$D_IN = !MUX_proc_m7_pff_rv$port0__write_1__PSEL_1 ;
  assign proc_m13_stall$EN =
	     WILL_FIRE_RL_proc_m13_repSt || WILL_FIRE_RL_proc_m13_repLdZ ||
	     WILL_FIRE_RL_proc_m13_repLd ||
	     WILL_FIRE_RL_proc_m13_reqSt ||
	     WILL_FIRE_RL_proc_m13_reqLd ;

  // register proc_m13_stalled
  assign proc_m13_stalled$D_IN = proc_m9_pff_rv[195:32] ;
  assign proc_m13_stalled$EN = MUX_proc_m13_stall$write_1__SEL_2 ;

  // register proc_m1_readRq
  assign proc_m1_readRq$D_IN = !MUX_proc_m1_readRq$write_1__SEL_1 ;
  assign proc_m1_readRq$EN =
	     WILL_FIRE_RL_proc_m10_instFetchRsIgnore ||
	     WILL_FIRE_RL_proc_m10_instFetchRs ||
	     WILL_FIRE_RL_proc_m10_instFetchRq ;

  // register proc_m2_btbTags
  assign proc_m2_btbTags$D_IN =
	     { (proc_m7_pff_rv$port1__read[16:14] == 3'd7) ?
		 proc_m7_pff_rv$port1__read[23:17] :
		 proc_m2_btbTags[55:49],
	       (proc_m7_pff_rv$port1__read[16:14] == 3'd6) ?
		 proc_m7_pff_rv$port1__read[23:17] :
		 proc_m2_btbTags[48:42],
	       (proc_m7_pff_rv$port1__read[16:14] == 3'd5) ?
		 proc_m7_pff_rv$port1__read[23:17] :
		 proc_m2_btbTags[41:35],
	       (proc_m7_pff_rv$port1__read[16:14] == 3'd4) ?
		 proc_m7_pff_rv$port1__read[23:17] :
		 proc_m2_btbTags[34:28],
	       (proc_m7_pff_rv$port1__read[16:14] == 3'd3) ?
		 proc_m7_pff_rv$port1__read[23:17] :
		 proc_m2_btbTags[27:21],
	       (proc_m7_pff_rv$port1__read[16:14] == 3'd2) ?
		 proc_m7_pff_rv$port1__read[23:17] :
		 proc_m2_btbTags[20:14],
	       (proc_m7_pff_rv$port1__read[16:14] == 3'd1) ?
		 proc_m7_pff_rv$port1__read[23:17] :
		 proc_m2_btbTags[13:7],
	       (proc_m7_pff_rv$port1__read[16:14] == 3'd0) ?
		 proc_m7_pff_rv$port1__read[23:17] :
		 proc_m2_btbTags[6:0] } ;
  assign proc_m2_btbTags$EN =
	     WILL_FIRE_RL_proc_m10_modifyPc &&
	     !proc_m7_pff_rv_port1__read__4_BITS_11_TO_2_6_E_ETC___d59 ;

  // register proc_m2_btbTargets
  assign proc_m2_btbTargets$D_IN =
	     { (proc_m7_pff_rv$port1__read[16:14] == 3'd7) ?
		 proc_m7_pff_rv$port1__read[11:2] :
		 proc_m2_btbTargets[79:70],
	       (proc_m7_pff_rv$port1__read[16:14] == 3'd6) ?
		 proc_m7_pff_rv$port1__read[11:2] :
		 proc_m2_btbTargets[69:60],
	       (proc_m7_pff_rv$port1__read[16:14] == 3'd5) ?
		 proc_m7_pff_rv$port1__read[11:2] :
		 proc_m2_btbTargets[59:50],
	       (proc_m7_pff_rv$port1__read[16:14] == 3'd4) ?
		 proc_m7_pff_rv$port1__read[11:2] :
		 proc_m2_btbTargets[49:40],
	       (proc_m7_pff_rv$port1__read[16:14] == 3'd3) ?
		 proc_m7_pff_rv$port1__read[11:2] :
		 proc_m2_btbTargets[39:30],
	       (proc_m7_pff_rv$port1__read[16:14] == 3'd2) ?
		 proc_m7_pff_rv$port1__read[11:2] :
		 proc_m2_btbTargets[29:20],
	       (proc_m7_pff_rv$port1__read[16:14] == 3'd1) ?
		 proc_m7_pff_rv$port1__read[11:2] :
		 proc_m2_btbTargets[19:10],
	       (proc_m7_pff_rv$port1__read[16:14] == 3'd0) ?
		 proc_m7_pff_rv$port1__read[11:2] :
		 proc_m2_btbTargets[9:0] } ;
  assign proc_m2_btbTargets$EN =
	     WILL_FIRE_RL_proc_m10_modifyPc &&
	     !proc_m7_pff_rv_port1__read__4_BITS_11_TO_2_6_E_ETC___d59 ;

  // register proc_m2_btbValid
  assign proc_m2_btbValid$D_IN =
	     proc_m7_pff_rv_port1__read__4_BITS_11_TO_2_6_E_ETC___d59 ?
	       { proc_m7_pff_rv$port1__read[16:14] != 3'd7 &&
		 proc_m2_btbValid[7],
		 proc_m7_pff_rv$port1__read[16:14] != 3'd6 &&
		 proc_m2_btbValid[6],
		 proc_m7_pff_rv$port1__read[16:14] != 3'd5 &&
		 proc_m2_btbValid[5],
		 proc_m7_pff_rv$port1__read[16:14] != 3'd4 &&
		 proc_m2_btbValid[4],
		 proc_m7_pff_rv$port1__read[16:14] != 3'd3 &&
		 proc_m2_btbValid[3],
		 proc_m7_pff_rv$port1__read[16:14] != 3'd2 &&
		 proc_m2_btbValid[2],
		 proc_m7_pff_rv$port1__read[16:14] != 3'd1 &&
		 proc_m2_btbValid[1],
		 proc_m7_pff_rv$port1__read[16:14] != 3'd0 &&
		 proc_m2_btbValid[0] } :
	       { proc_m7_pff_rv$port1__read[16:14] == 3'd7 ||
		 proc_m2_btbValid[7],
		 proc_m7_pff_rv$port1__read[16:14] == 3'd6 ||
		 proc_m2_btbValid[6],
		 proc_m7_pff_rv$port1__read[16:14] == 3'd5 ||
		 proc_m2_btbValid[5],
		 proc_m7_pff_rv$port1__read[16:14] == 3'd4 ||
		 proc_m2_btbValid[4],
		 proc_m7_pff_rv$port1__read[16:14] == 3'd3 ||
		 proc_m2_btbValid[3],
		 proc_m7_pff_rv$port1__read[16:14] == 3'd2 ||
		 proc_m2_btbValid[2],
		 proc_m7_pff_rv$port1__read[16:14] == 3'd1 ||
		 proc_m2_btbValid[1],
		 proc_m7_pff_rv$port1__read[16:14] == 3'd0 ||
		 proc_m2_btbValid[0] } ;
  assign proc_m2_btbValid$EN =
	     WILL_FIRE_RL_proc_m10_modifyPc &&
	     (proc_m7_pff_rv$port1__read[23:17] ==
	      CASE_proc_m7_pff_rvport1__read_BITS_16_TO_14__ETC__q14 ||
	      !proc_m7_pff_rv_port1__read__4_BITS_11_TO_2_6_E_ETC___d59) ;

  // register proc_m3_pff_rv
  assign proc_m3_pff_rv$D_IN = proc_m3_pff_rv$port3__read ;
  assign proc_m3_pff_rv$EN = 1'b1 ;

  // register proc_m4_rf
  assign proc_m4_rf$D_IN =
	     WILL_FIRE_RL_proc_m13_repLd ?
	       MUX_proc_m4_rf$write_1__VAL_1 :
	       MUX_proc_m4_rf$write_1__VAL_2 ;
  assign proc_m4_rf$EN =
	     WILL_FIRE_RL_proc_m13_repLd || WILL_FIRE_RL_proc_m13_wbNm ;

  // register proc_m5_sbFlags
  always@(MUX_proc_m5_sbFlags$write_1__SEL_1 or
	  MUX_proc_m5_sbFlags$write_1__VAL_1 or
	  MUX_proc_m7_pff_rv$port0__write_1__PSEL_2 or
	  MUX_proc_m5_sbFlags$write_1__SEL_3 or
	  MUX_proc_m5_sbFlags$write_1__VAL_3 or
	  WILL_FIRE_RL_proc_m11_decodeLd or
	  MUX_proc_m5_sbFlags$write_1__VAL_4 or
	  WILL_FIRE_RL_proc_m11_decodeNm or
	  MUX_proc_m5_sbFlags$write_1__VAL_5)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_proc_m5_sbFlags$write_1__SEL_1:
	  proc_m5_sbFlags$D_IN = MUX_proc_m5_sbFlags$write_1__VAL_1;
      MUX_proc_m7_pff_rv$port0__write_1__PSEL_2:
	  proc_m5_sbFlags$D_IN = MUX_proc_m5_sbFlags$write_1__VAL_1;
      MUX_proc_m5_sbFlags$write_1__SEL_3:
	  proc_m5_sbFlags$D_IN = MUX_proc_m5_sbFlags$write_1__VAL_3;
      WILL_FIRE_RL_proc_m11_decodeLd:
	  proc_m5_sbFlags$D_IN = MUX_proc_m5_sbFlags$write_1__VAL_4;
      WILL_FIRE_RL_proc_m11_decodeNm:
	  proc_m5_sbFlags$D_IN = MUX_proc_m5_sbFlags$write_1__VAL_5;
      default: proc_m5_sbFlags$D_IN = 32'hAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign proc_m5_sbFlags$EN =
	     WILL_FIRE_RL_proc_m13_wrongEpoch &&
	     (proc_m9_pff_rv[195:194] == 2'h0 ||
	      proc_m9_pff_rv[195:194] == 2'h3) ||
	     WILL_FIRE_RL_proc_m13_wbNmZ ||
	     WILL_FIRE_RL_proc_m13_wbNm ||
	     WILL_FIRE_RL_proc_m13_repLdZ ||
	     WILL_FIRE_RL_proc_m13_repLd ||
	     WILL_FIRE_RL_proc_m11_decodeLd ||
	     WILL_FIRE_RL_proc_m11_decodeNm ;

  // register proc_m6_pff_rv
  assign proc_m6_pff_rv$D_IN = proc_m6_pff_rv$port2__read ;
  assign proc_m6_pff_rv$EN = 1'b1 ;

  // register proc_m7_pff_rv
  assign proc_m7_pff_rv$D_IN = proc_m7_pff_rv$port2__read ;
  assign proc_m7_pff_rv$EN = 1'b1 ;

  // register proc_m8_eEpoch
  assign proc_m8_eEpoch$D_IN =
	     MUX_proc_m8_eEpoch$write_1__SEL_1 ?
	       !proc_m8_eEpoch :
	       !proc_m8_eEpoch ;
  assign proc_m8_eEpoch$EN =
	     (WILL_FIRE_RL_proc_m13_repSt || WILL_FIRE_RL_proc_m13_repLdZ ||
	      WILL_FIRE_RL_proc_m13_repLd) &&
	     NOT_IF_proc_m13_stalled_23_BITS_31_TO_25_06_EQ_ETC___d950 ||
	     (WILL_FIRE_RL_proc_m13_wbNmZ || WILL_FIRE_RL_proc_m13_wbNm) &&
	     NOT_IF_proc_m9_pff_rv_port0__read__83_BITS_63__ETC___d1060 ;

  // register proc_m9_pff_rv
  assign proc_m9_pff_rv$D_IN = proc_m9_pff_rv$port2__read ;
  assign proc_m9_pff_rv$EN = 1'b1 ;

  // submodule proc_m1_bram
  assign proc_m1_bram$readRq_idx = proc_m10_pc[11:2] ;
  assign proc_m1_bram$write_d = rss$D_OUT ;
  assign proc_m1_bram$write_idx = proc_m10_pinitRsOfs ;
  assign proc_m1_bram$EN_readRq = WILL_FIRE_RL_proc_m10_instFetchRq ;
  assign proc_m1_bram$EN_write =
	     WILL_FIRE_RL_proc_m10_pgmInitRsEnd ||
	     WILL_FIRE_RL_proc_m10_pgmInitRs ;

  // submodule rqs
  always@(MUX_rqs$enq_1__SEL_1 or
	  MUX_rqs$enq_1__VAL_1 or
	  WILL_FIRE_RL_proc_m13_reqLd or
	  MUX_rqs$enq_1__VAL_2 or
	  WILL_FIRE_RL_proc_m13_reqSt or MUX_rqs$enq_1__VAL_3)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_rqs$enq_1__SEL_1: rqs$D_IN = MUX_rqs$enq_1__VAL_1;
      WILL_FIRE_RL_proc_m13_reqLd: rqs$D_IN = MUX_rqs$enq_1__VAL_2;
      WILL_FIRE_RL_proc_m13_reqSt: rqs$D_IN = MUX_rqs$enq_1__VAL_3;
      default: rqs$D_IN = 69'h0AAAAAAAAAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign rqs$ENQ =
	     WILL_FIRE_RL_proc_m10_pgmInitRqEnd ||
	     WILL_FIRE_RL_proc_m10_pgmInitRq ||
	     WILL_FIRE_RL_proc_m13_reqLd ||
	     WILL_FIRE_RL_proc_m13_reqSt ;
  assign rqs$DEQ = EN_obtain_rq_get ;
  assign rqs$CLR = 1'b0 ;

  // submodule rss
  assign rss$D_IN = send_rs_put ;
  assign rss$ENQ = EN_send_rs_put ;
  assign rss$DEQ =
	     WILL_FIRE_RL_proc_m13_repSt || WILL_FIRE_RL_proc_m13_repLdZ ||
	     WILL_FIRE_RL_proc_m13_repLd ||
	     WILL_FIRE_RL_proc_m10_pgmInitRsEnd ||
	     WILL_FIRE_RL_proc_m10_pgmInitRs ;
  assign rss$CLR = 1'b0 ;

  // remaining internal signals
  assign IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d757 =
	     { (proc_m13_stalled[161:157] == 5'd31) ?
		 x_9__h57090 :
		 proc_m4_rf[1023:992],
	       (proc_m13_stalled[161:157] == 5'd30) ?
		 x_9__h57090 :
		 proc_m4_rf[991:960],
	       (proc_m13_stalled[161:157] == 5'd29) ?
		 x_9__h57090 :
		 proc_m4_rf[959:928],
	       (proc_m13_stalled[161:157] == 5'd28) ?
		 x_9__h57090 :
		 proc_m4_rf[927:896] } ;
  assign IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d762 =
	     { IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d757,
	       (proc_m13_stalled[161:157] == 5'd27) ?
		 x_9__h57090 :
		 proc_m4_rf[895:864],
	       (proc_m13_stalled[161:157] == 5'd26) ?
		 x_9__h57090 :
		 proc_m4_rf[863:832] } ;
  assign IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d767 =
	     { IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d762,
	       (proc_m13_stalled[161:157] == 5'd25) ?
		 x_9__h57090 :
		 proc_m4_rf[831:800],
	       (proc_m13_stalled[161:157] == 5'd24) ?
		 x_9__h57090 :
		 proc_m4_rf[799:768] } ;
  assign IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d772 =
	     { IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d767,
	       (proc_m13_stalled[161:157] == 5'd23) ?
		 x_9__h57090 :
		 proc_m4_rf[767:736],
	       (proc_m13_stalled[161:157] == 5'd22) ?
		 x_9__h57090 :
		 proc_m4_rf[735:704] } ;
  assign IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d777 =
	     { IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d772,
	       (proc_m13_stalled[161:157] == 5'd21) ?
		 x_9__h57090 :
		 proc_m4_rf[703:672],
	       (proc_m13_stalled[161:157] == 5'd20) ?
		 x_9__h57090 :
		 proc_m4_rf[671:640] } ;
  assign IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d782 =
	     { IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d777,
	       (proc_m13_stalled[161:157] == 5'd19) ?
		 x_9__h57090 :
		 proc_m4_rf[639:608],
	       (proc_m13_stalled[161:157] == 5'd18) ?
		 x_9__h57090 :
		 proc_m4_rf[607:576] } ;
  assign IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d787 =
	     { IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d782,
	       (proc_m13_stalled[161:157] == 5'd17) ?
		 x_9__h57090 :
		 proc_m4_rf[575:544],
	       (proc_m13_stalled[161:157] == 5'd16) ?
		 x_9__h57090 :
		 proc_m4_rf[543:512] } ;
  assign IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d792 =
	     { IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d787,
	       (proc_m13_stalled[161:157] == 5'd15) ?
		 x_9__h57090 :
		 proc_m4_rf[511:480],
	       (proc_m13_stalled[161:157] == 5'd14) ?
		 x_9__h57090 :
		 proc_m4_rf[479:448] } ;
  assign IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d797 =
	     { IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d792,
	       (proc_m13_stalled[161:157] == 5'd13) ?
		 x_9__h57090 :
		 proc_m4_rf[447:416],
	       (proc_m13_stalled[161:157] == 5'd12) ?
		 x_9__h57090 :
		 proc_m4_rf[415:384] } ;
  assign IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d802 =
	     { IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d797,
	       (proc_m13_stalled[161:157] == 5'd11) ?
		 x_9__h57090 :
		 proc_m4_rf[383:352],
	       (proc_m13_stalled[161:157] == 5'd10) ?
		 x_9__h57090 :
		 proc_m4_rf[351:320] } ;
  assign IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d807 =
	     { IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d802,
	       (proc_m13_stalled[161:157] == 5'd9) ?
		 x_9__h57090 :
		 proc_m4_rf[319:288],
	       (proc_m13_stalled[161:157] == 5'd8) ?
		 x_9__h57090 :
		 proc_m4_rf[287:256] } ;
  assign IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d812 =
	     { IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d807,
	       (proc_m13_stalled[161:157] == 5'd7) ?
		 x_9__h57090 :
		 proc_m4_rf[255:224],
	       (proc_m13_stalled[161:157] == 5'd6) ?
		 x_9__h57090 :
		 proc_m4_rf[223:192] } ;
  assign IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d817 =
	     { IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d812,
	       (proc_m13_stalled[161:157] == 5'd5) ?
		 x_9__h57090 :
		 proc_m4_rf[191:160],
	       (proc_m13_stalled[161:157] == 5'd4) ?
		 x_9__h57090 :
		 proc_m4_rf[159:128] } ;
  assign IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d822 =
	     { IF_proc_m13_stalled_23_BITS_161_TO_157_24_EQ_3_ETC___d817,
	       (proc_m13_stalled[161:157] == 5'd3) ?
		 x_9__h57090 :
		 proc_m4_rf[127:96],
	       (proc_m13_stalled[161:157] == 5'd2) ?
		 x_9__h57090 :
		 proc_m4_rf[95:64] } ;
  assign NOT_IF_proc_m13_stalled_23_BITS_31_TO_25_06_EQ_ETC___d950 =
	     x_15__h62477 != proc_m13_stalled[12:1] ;
  assign NOT_IF_proc_m9_pff_rv_port0__read__83_BITS_63__ETC___d1060 =
	     x_13__h75921 != proc_m9_pff_rv[44:33] ;
  assign NOT_SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m_ETC___d386 =
	     !SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 &&
	     !SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 &&
	     !CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 &&
	     proc_m3_pff_rv[31:25] != 7'h03 &&
	     proc_m3_pff_rv[31:25] != 7'h23 &&
	     !proc_m6_pff_rv$port1__read[164] ;
  assign NOT_proc_m7_pff_rv_port0__read__73_BIT_24_74_7_ETC___d359 =
	     !proc_m7_pff_rv[24] &&
	     !SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 &&
	     !SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 &&
	     proc_m3_pff_rv[31:25] == 7'h23 &&
	     !proc_m6_pff_rv$port1__read[164] ;
  assign SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d1028 =
	     x__h76086 == y__h76221 ;
  assign SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d1040 =
	     (x__h76086 ^ 32'h80000000) < (y__h76221 ^ 32'h80000000) ;
  assign SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d1045 =
	     x__h76086 < y__h76221 ;
  assign SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d921 =
	     x__h62644 == y__h62779 ;
  assign SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d931 =
	     (x__h62644 ^ 32'h80000000) < (y__h62779 ^ 32'h80000000) ;
  assign SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d935 =
	     x__h62644 < y__h62779 ;
  assign proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_0x4___d928 =
	     proc_m13_stalled[24:13] + 12'h004 ;
  assign proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_proc_ETC___d927 =
	     proc_m13_stalled[24:13] + y__h62891 ;
  assign proc_m3_pff_rv_BITS_56_TO_45__q1 = proc_m3_pff_rv[56:45] ;
  assign proc_m3_pff_rv_port0__read__76_BIT_57_77_AND_N_ETC___d226 =
	     proc_m3_pff_rv[57] &&
	     !SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 &&
	     !CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 &&
	     proc_m3_pff_rv[31:25] == 7'h03 &&
	     !proc_m6_pff_rv$port1__read[164] ;
  assign proc_m6_pff_rv_BITS_120_TO_89__q3 = proc_m6_pff_rv[120:89] ;
  assign proc_m6_pff_rv_BITS_56_TO_45__q2 = proc_m6_pff_rv[56:45] ;
  assign proc_m7_pff_rv_port1__read__4_BITS_11_TO_2_6_E_ETC___d59 =
	     proc_m7_pff_rv$port1__read[11:2] ==
	     proc_m7_pff_rv$port1__read[23:14] + 10'h001 ;
  assign proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1034 =
	     proc_m9_pff_rv[56:45] + y__h76333 ;
  assign proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1035 =
	     proc_m9_pff_rv[56:45] + 12'h004 ;
  assign proc_m9_pff_rv_port0__read__83_BIT_32_85_EQ_pr_ETC___d587 =
	     proc_m9_pff_rv[32] == proc_m8_eEpoch ;
  assign rssD_OUT_BITS_15_TO_0__q9 = rss$D_OUT[15:0] ;
  assign rssD_OUT_BITS_7_TO_0__q8 = rss$D_OUT[7:0] ;
  assign v__h34530 =
	     (CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbVali_ETC__q10 &&
	      proc_m10_pc[11:5] ==
	      CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbTags_ETC__q11) ?
	       x_6__h34631 :
	       x_6__h34648 ;
  assign x_5__h34653 = { v__h34530, 2'h0 } ;
  assign x_5__h44387 =
	     (proc_m3_pff_rv[31:25] == 7'h63) ? 5'h0 : proc_m3_pff_rv[36:32] ;
  assign x_6__h34648 = proc_m10_pc[11:2] + 10'h001 ;
  assign x_9__h36794 =
	     { {20{proc_m3_pff_rv_BITS_56_TO_45__q1[11]}},
	       proc_m3_pff_rv_BITS_56_TO_45__q1 } ;
  assign x__h28884 = ~proc_m10_pinitRqOfs ;
  assign x__h28916 = { 20'h0, proc_m10_pinitRqOfs, 2'h0 } ;
  assign x__h29980 = ~proc_m10_pinitRsOfs ;
  assign x__h36894 =
	     SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 +
	     x_9__h36794 ;
  assign x__h42154 =
	     SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 +
	     { {20{x__h42204[11]}}, x__h42204 } ;
  assign x__h42204 = { proc_m3_pff_rv[56:50], proc_m3_pff_rv[36:32] } ;
  assign x__h49213 = { 20'd0, proc_m6_pff_rv[24:13] } ;
  assign x__h49264 = proc_m6_pff_rv[24:13] + 12'h004 ;
  assign y__h49354 =
	     { {20{proc_m6_pff_rv_BITS_56_TO_45__q2[11]}},
	       proc_m6_pff_rv_BITS_56_TO_45__q2 } ;
  assign y__h62528 = { proc_m13_stalled[45], proc_m13_stalled[55:46], 1'h0 } ;
  assign y__h62891 =
	     { proc_m13_stalled[32],
	       proc_m13_stalled[55:50],
	       proc_m13_stalled[36:33],
	       1'h0 } ;
  assign y__h75970 = { proc_m9_pff_rv[77], proc_m9_pff_rv[87:78], 1'h0 } ;
  assign y__h76333 =
	     { proc_m9_pff_rv[64],
	       proc_m9_pff_rv[87:82],
	       proc_m9_pff_rv[68:65],
	       1'h0 } ;
  always@(proc_m3_pff_rv)
  begin
    case (proc_m3_pff_rv[31:25])
      7'h03: x_4__h35126 = 2'h0;
      7'h23: x_4__h35126 = 2'h1;
      default: x_4__h35126 = 2'h3;
    endcase
  end
  always@(proc_m3_pff_rv or proc_m4_rf)
  begin
    case (proc_m3_pff_rv[49:45])
      5'd0: x__h44170 = proc_m4_rf[31:0];
      5'd1: x__h44170 = proc_m4_rf[63:32];
      5'd2: x__h44170 = proc_m4_rf[95:64];
      5'd3: x__h44170 = proc_m4_rf[127:96];
      5'd4: x__h44170 = proc_m4_rf[159:128];
      5'd5: x__h44170 = proc_m4_rf[191:160];
      5'd6: x__h44170 = proc_m4_rf[223:192];
      5'd7: x__h44170 = proc_m4_rf[255:224];
      5'd8: x__h44170 = proc_m4_rf[287:256];
      5'd9: x__h44170 = proc_m4_rf[319:288];
      5'd10: x__h44170 = proc_m4_rf[351:320];
      5'd11: x__h44170 = proc_m4_rf[383:352];
      5'd12: x__h44170 = proc_m4_rf[415:384];
      5'd13: x__h44170 = proc_m4_rf[447:416];
      5'd14: x__h44170 = proc_m4_rf[479:448];
      5'd15: x__h44170 = proc_m4_rf[511:480];
      5'd16: x__h44170 = proc_m4_rf[543:512];
      5'd17: x__h44170 = proc_m4_rf[575:544];
      5'd18: x__h44170 = proc_m4_rf[607:576];
      5'd19: x__h44170 = proc_m4_rf[639:608];
      5'd20: x__h44170 = proc_m4_rf[671:640];
      5'd21: x__h44170 = proc_m4_rf[703:672];
      5'd22: x__h44170 = proc_m4_rf[735:704];
      5'd23: x__h44170 = proc_m4_rf[767:736];
      5'd24: x__h44170 = proc_m4_rf[799:768];
      5'd25: x__h44170 = proc_m4_rf[831:800];
      5'd26: x__h44170 = proc_m4_rf[863:832];
      5'd27: x__h44170 = proc_m4_rf[895:864];
      5'd28: x__h44170 = proc_m4_rf[927:896];
      5'd29: x__h44170 = proc_m4_rf[959:928];
      5'd30: x__h44170 = proc_m4_rf[991:960];
      5'd31: x__h44170 = proc_m4_rf[1023:992];
    endcase
  end
  always@(proc_m6_pff_rv or proc_m6_pff_rv_BITS_120_TO_89__q3 or y__h49354)
  begin
    case (proc_m6_pff_rv[39:37])
      3'h0:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q4 =
	      proc_m6_pff_rv[120:89] + y__h49354;
      3'h2:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q4 =
	      ((proc_m6_pff_rv[120:89] ^ 32'h80000000) <
	       (y__h49354 ^ 32'h80000000)) ?
		32'h00000001 :
		32'h0;
      3'h3:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q4 =
	      (proc_m6_pff_rv[120:89] < y__h49354) ? 32'h00000001 : 32'h0;
      3'h4:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q4 =
	      proc_m6_pff_rv[120:89] ^ y__h49354;
      3'h6:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q4 =
	      proc_m6_pff_rv[120:89] | y__h49354;
      3'h7:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q4 =
	      proc_m6_pff_rv[120:89] & y__h49354;
      default: CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q4 =
		   (proc_m6_pff_rv[56:51] == 6'h0 &&
		    proc_m6_pff_rv[39:37] == 3'h1 &&
		    !proc_m6_pff_rv[50]) ?
		     proc_m6_pff_rv[120:89] << proc_m6_pff_rv[49:45] :
		     ((proc_m6_pff_rv[56:51] == 6'h0 &&
		       proc_m6_pff_rv[39:37] == 3'h5 &&
		       !proc_m6_pff_rv[50]) ?
			proc_m6_pff_rv[120:89] >> proc_m6_pff_rv[49:45] :
			((proc_m6_pff_rv[56:51] == 6'h10 &&
			  proc_m6_pff_rv[39:37] == 3'h5 &&
			  !proc_m6_pff_rv[50]) ?
			   proc_m6_pff_rv[120:89] >> proc_m6_pff_rv[49:45] |
			   ~(32'hFFFFFFFF >> proc_m6_pff_rv[49:45]) &
			   {32{proc_m6_pff_rv_BITS_120_TO_89__q3[31]}} :
			   32'h0));
    endcase
  end
  always@(proc_m6_pff_rv)
  begin
    case (proc_m6_pff_rv[39:37])
      3'h0:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q5 =
	      proc_m6_pff_rv[120:89] + proc_m6_pff_rv[88:57];
      3'h1:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q5 =
	      proc_m6_pff_rv[120:89] << proc_m6_pff_rv[61:57];
      3'h2:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q5 =
	      ((proc_m6_pff_rv[120:89] ^ 32'h80000000) <
	       (proc_m6_pff_rv[88:57] ^ 32'h80000000)) ?
		32'h00000001 :
		32'h0;
      3'h3:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q5 =
	      (proc_m6_pff_rv[120:89] < proc_m6_pff_rv[88:57]) ?
		32'h00000001 :
		32'h0;
      3'h4:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q5 =
	      proc_m6_pff_rv[120:89] ^ proc_m6_pff_rv[88:57];
      3'h5:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q5 =
	      proc_m6_pff_rv[120:89] >> proc_m6_pff_rv[61:57];
      3'h6:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q5 =
	      proc_m6_pff_rv[120:89] | proc_m6_pff_rv[88:57];
      3'h7:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q5 =
	      proc_m6_pff_rv[120:89] & proc_m6_pff_rv[88:57];
    endcase
  end
  always@(proc_m6_pff_rv or proc_m6_pff_rv_BITS_120_TO_89__q3)
  begin
    case (proc_m6_pff_rv[39:37])
      3'h0:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q6 =
	      proc_m6_pff_rv[120:89] - proc_m6_pff_rv[88:57];
      3'h5:
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q6 =
	      proc_m6_pff_rv[120:89] >> proc_m6_pff_rv[61:57] |
	      ~(32'hFFFFFFFF >> proc_m6_pff_rv[61:57]) &
	      {32{proc_m6_pff_rv_BITS_120_TO_89__q3[31]}};
      default: CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q6 = 32'h0;
    endcase
  end
  always@(proc_m6_pff_rv or
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q5 or
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q6)
  begin
    case (proc_m6_pff_rv[56:50])
      7'h0:
	  CASE_proc_m6_pff_rv_BITS_56_TO_50_0x0_CASE_pro_ETC__q7 =
	      CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q5;
      7'h20:
	  CASE_proc_m6_pff_rv_BITS_56_TO_50_0x0_CASE_pro_ETC__q7 =
	      CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q6;
      default: CASE_proc_m6_pff_rv_BITS_56_TO_50_0x0_CASE_pro_ETC__q7 = 32'h0;
    endcase
  end
  always@(proc_m6_pff_rv or
	  CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q4 or
	  x__h49213 or
	  CASE_proc_m6_pff_rv_BITS_56_TO_50_0x0_CASE_pro_ETC__q7 or x__h49264)
  begin
    case (proc_m6_pff_rv[31:25])
      7'h13:
	  x_6__h48433 =
	      CASE_proc_m6_pff_rv_BITS_39_TO_37_0x0_proc_m6__ETC__q4;
      7'h17: x_6__h48433 = x__h49213 + { proc_m6_pff_rv[56:37], 12'h0 };
      7'h33:
	  x_6__h48433 =
	      CASE_proc_m6_pff_rv_BITS_56_TO_50_0x0_CASE_pro_ETC__q7;
      7'h37: x_6__h48433 = { proc_m6_pff_rv[56:37], 12'h0 };
      7'h67, 7'h6F: x_6__h48433 = { 20'd0, x__h49264 };
      default: x_6__h48433 = 32'h0;
    endcase
  end
  always@(proc_m13_stalled or proc_m4_rf)
  begin
    case (proc_m13_stalled[44:40])
      5'd0: x__h62644 = proc_m4_rf[31:0];
      5'd1: x__h62644 = proc_m4_rf[63:32];
      5'd2: x__h62644 = proc_m4_rf[95:64];
      5'd3: x__h62644 = proc_m4_rf[127:96];
      5'd4: x__h62644 = proc_m4_rf[159:128];
      5'd5: x__h62644 = proc_m4_rf[191:160];
      5'd6: x__h62644 = proc_m4_rf[223:192];
      5'd7: x__h62644 = proc_m4_rf[255:224];
      5'd8: x__h62644 = proc_m4_rf[287:256];
      5'd9: x__h62644 = proc_m4_rf[319:288];
      5'd10: x__h62644 = proc_m4_rf[351:320];
      5'd11: x__h62644 = proc_m4_rf[383:352];
      5'd12: x__h62644 = proc_m4_rf[415:384];
      5'd13: x__h62644 = proc_m4_rf[447:416];
      5'd14: x__h62644 = proc_m4_rf[479:448];
      5'd15: x__h62644 = proc_m4_rf[511:480];
      5'd16: x__h62644 = proc_m4_rf[543:512];
      5'd17: x__h62644 = proc_m4_rf[575:544];
      5'd18: x__h62644 = proc_m4_rf[607:576];
      5'd19: x__h62644 = proc_m4_rf[639:608];
      5'd20: x__h62644 = proc_m4_rf[671:640];
      5'd21: x__h62644 = proc_m4_rf[703:672];
      5'd22: x__h62644 = proc_m4_rf[735:704];
      5'd23: x__h62644 = proc_m4_rf[767:736];
      5'd24: x__h62644 = proc_m4_rf[799:768];
      5'd25: x__h62644 = proc_m4_rf[831:800];
      5'd26: x__h62644 = proc_m4_rf[863:832];
      5'd27: x__h62644 = proc_m4_rf[895:864];
      5'd28: x__h62644 = proc_m4_rf[927:896];
      5'd29: x__h62644 = proc_m4_rf[959:928];
      5'd30: x__h62644 = proc_m4_rf[991:960];
      5'd31: x__h62644 = proc_m4_rf[1023:992];
    endcase
  end
  always@(proc_m13_stalled or proc_m4_rf)
  begin
    case (proc_m13_stalled[49:45])
      5'd0: y__h62779 = proc_m4_rf[31:0];
      5'd1: y__h62779 = proc_m4_rf[63:32];
      5'd2: y__h62779 = proc_m4_rf[95:64];
      5'd3: y__h62779 = proc_m4_rf[127:96];
      5'd4: y__h62779 = proc_m4_rf[159:128];
      5'd5: y__h62779 = proc_m4_rf[191:160];
      5'd6: y__h62779 = proc_m4_rf[223:192];
      5'd7: y__h62779 = proc_m4_rf[255:224];
      5'd8: y__h62779 = proc_m4_rf[287:256];
      5'd9: y__h62779 = proc_m4_rf[319:288];
      5'd10: y__h62779 = proc_m4_rf[351:320];
      5'd11: y__h62779 = proc_m4_rf[383:352];
      5'd12: y__h62779 = proc_m4_rf[415:384];
      5'd13: y__h62779 = proc_m4_rf[447:416];
      5'd14: y__h62779 = proc_m4_rf[479:448];
      5'd15: y__h62779 = proc_m4_rf[511:480];
      5'd16: y__h62779 = proc_m4_rf[543:512];
      5'd17: y__h62779 = proc_m4_rf[575:544];
      5'd18: y__h62779 = proc_m4_rf[607:576];
      5'd19: y__h62779 = proc_m4_rf[639:608];
      5'd20: y__h62779 = proc_m4_rf[671:640];
      5'd21: y__h62779 = proc_m4_rf[703:672];
      5'd22: y__h62779 = proc_m4_rf[735:704];
      5'd23: y__h62779 = proc_m4_rf[767:736];
      5'd24: y__h62779 = proc_m4_rf[799:768];
      5'd25: y__h62779 = proc_m4_rf[831:800];
      5'd26: y__h62779 = proc_m4_rf[863:832];
      5'd27: y__h62779 = proc_m4_rf[895:864];
      5'd28: y__h62779 = proc_m4_rf[927:896];
      5'd29: y__h62779 = proc_m4_rf[959:928];
      5'd30: y__h62779 = proc_m4_rf[991:960];
      5'd31: y__h62779 = proc_m4_rf[1023:992];
    endcase
  end
  always@(proc_m10_pc or proc_m2_btbTargets)
  begin
    case (proc_m10_pc[4:2])
      3'd0: x_6__h34631 = proc_m2_btbTargets[9:0];
      3'd1: x_6__h34631 = proc_m2_btbTargets[19:10];
      3'd2: x_6__h34631 = proc_m2_btbTargets[29:20];
      3'd3: x_6__h34631 = proc_m2_btbTargets[39:30];
      3'd4: x_6__h34631 = proc_m2_btbTargets[49:40];
      3'd5: x_6__h34631 = proc_m2_btbTargets[59:50];
      3'd6: x_6__h34631 = proc_m2_btbTargets[69:60];
      3'd7: x_6__h34631 = proc_m2_btbTargets[79:70];
    endcase
  end
  always@(proc_m9_pff_rv or proc_m4_rf)
  begin
    case (proc_m9_pff_rv[76:72])
      5'd0: x__h76086 = proc_m4_rf[31:0];
      5'd1: x__h76086 = proc_m4_rf[63:32];
      5'd2: x__h76086 = proc_m4_rf[95:64];
      5'd3: x__h76086 = proc_m4_rf[127:96];
      5'd4: x__h76086 = proc_m4_rf[159:128];
      5'd5: x__h76086 = proc_m4_rf[191:160];
      5'd6: x__h76086 = proc_m4_rf[223:192];
      5'd7: x__h76086 = proc_m4_rf[255:224];
      5'd8: x__h76086 = proc_m4_rf[287:256];
      5'd9: x__h76086 = proc_m4_rf[319:288];
      5'd10: x__h76086 = proc_m4_rf[351:320];
      5'd11: x__h76086 = proc_m4_rf[383:352];
      5'd12: x__h76086 = proc_m4_rf[415:384];
      5'd13: x__h76086 = proc_m4_rf[447:416];
      5'd14: x__h76086 = proc_m4_rf[479:448];
      5'd15: x__h76086 = proc_m4_rf[511:480];
      5'd16: x__h76086 = proc_m4_rf[543:512];
      5'd17: x__h76086 = proc_m4_rf[575:544];
      5'd18: x__h76086 = proc_m4_rf[607:576];
      5'd19: x__h76086 = proc_m4_rf[639:608];
      5'd20: x__h76086 = proc_m4_rf[671:640];
      5'd21: x__h76086 = proc_m4_rf[703:672];
      5'd22: x__h76086 = proc_m4_rf[735:704];
      5'd23: x__h76086 = proc_m4_rf[767:736];
      5'd24: x__h76086 = proc_m4_rf[799:768];
      5'd25: x__h76086 = proc_m4_rf[831:800];
      5'd26: x__h76086 = proc_m4_rf[863:832];
      5'd27: x__h76086 = proc_m4_rf[895:864];
      5'd28: x__h76086 = proc_m4_rf[927:896];
      5'd29: x__h76086 = proc_m4_rf[959:928];
      5'd30: x__h76086 = proc_m4_rf[991:960];
      5'd31: x__h76086 = proc_m4_rf[1023:992];
    endcase
  end
  always@(proc_m9_pff_rv or proc_m4_rf)
  begin
    case (proc_m9_pff_rv[81:77])
      5'd0: y__h76221 = proc_m4_rf[31:0];
      5'd1: y__h76221 = proc_m4_rf[63:32];
      5'd2: y__h76221 = proc_m4_rf[95:64];
      5'd3: y__h76221 = proc_m4_rf[127:96];
      5'd4: y__h76221 = proc_m4_rf[159:128];
      5'd5: y__h76221 = proc_m4_rf[191:160];
      5'd6: y__h76221 = proc_m4_rf[223:192];
      5'd7: y__h76221 = proc_m4_rf[255:224];
      5'd8: y__h76221 = proc_m4_rf[287:256];
      5'd9: y__h76221 = proc_m4_rf[319:288];
      5'd10: y__h76221 = proc_m4_rf[351:320];
      5'd11: y__h76221 = proc_m4_rf[383:352];
      5'd12: y__h76221 = proc_m4_rf[415:384];
      5'd13: y__h76221 = proc_m4_rf[447:416];
      5'd14: y__h76221 = proc_m4_rf[479:448];
      5'd15: y__h76221 = proc_m4_rf[511:480];
      5'd16: y__h76221 = proc_m4_rf[543:512];
      5'd17: y__h76221 = proc_m4_rf[575:544];
      5'd18: y__h76221 = proc_m4_rf[607:576];
      5'd19: y__h76221 = proc_m4_rf[639:608];
      5'd20: y__h76221 = proc_m4_rf[671:640];
      5'd21: y__h76221 = proc_m4_rf[703:672];
      5'd22: y__h76221 = proc_m4_rf[735:704];
      5'd23: y__h76221 = proc_m4_rf[767:736];
      5'd24: y__h76221 = proc_m4_rf[799:768];
      5'd25: y__h76221 = proc_m4_rf[831:800];
      5'd26: y__h76221 = proc_m4_rf[863:832];
      5'd27: y__h76221 = proc_m4_rf[895:864];
      5'd28: y__h76221 = proc_m4_rf[927:896];
      5'd29: y__h76221 = proc_m4_rf[959:928];
      5'd30: y__h76221 = proc_m4_rf[991:960];
      5'd31: y__h76221 = proc_m4_rf[1023:992];
    endcase
  end
  always@(proc_m13_stalled or
	  rss$D_OUT or rssD_OUT_BITS_7_TO_0__q8 or rssD_OUT_BITS_15_TO_0__q9)
  begin
    case (proc_m13_stalled[39:37])
      3'h0:
	  x_9__h57090 =
	      { {24{rssD_OUT_BITS_7_TO_0__q8[7]}}, rssD_OUT_BITS_7_TO_0__q8 };
      3'h1:
	  x_9__h57090 =
	      { {16{rssD_OUT_BITS_15_TO_0__q9[15]}},
		rssD_OUT_BITS_15_TO_0__q9 };
      3'h4: x_9__h57090 = { 24'd0, rss$D_OUT[7:0] };
      3'h5: x_9__h57090 = { 16'd0, rss$D_OUT[15:0] };
      default: x_9__h57090 = rss$D_OUT;
    endcase
  end
  always@(proc_m10_pc or proc_m2_btbValid)
  begin
    case (proc_m10_pc[4:2])
      3'd0:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbVali_ETC__q10 =
	      proc_m2_btbValid[0];
      3'd1:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbVali_ETC__q10 =
	      proc_m2_btbValid[1];
      3'd2:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbVali_ETC__q10 =
	      proc_m2_btbValid[2];
      3'd3:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbVali_ETC__q10 =
	      proc_m2_btbValid[3];
      3'd4:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbVali_ETC__q10 =
	      proc_m2_btbValid[4];
      3'd5:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbVali_ETC__q10 =
	      proc_m2_btbValid[5];
      3'd6:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbVali_ETC__q10 =
	      proc_m2_btbValid[6];
      3'd7:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbVali_ETC__q10 =
	      proc_m2_btbValid[7];
    endcase
  end
  always@(proc_m10_pc or proc_m2_btbTags)
  begin
    case (proc_m10_pc[4:2])
      3'd0:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbTags_ETC__q11 =
	      proc_m2_btbTags[6:0];
      3'd1:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbTags_ETC__q11 =
	      proc_m2_btbTags[13:7];
      3'd2:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbTags_ETC__q11 =
	      proc_m2_btbTags[20:14];
      3'd3:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbTags_ETC__q11 =
	      proc_m2_btbTags[27:21];
      3'd4:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbTags_ETC__q11 =
	      proc_m2_btbTags[34:28];
      3'd5:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbTags_ETC__q11 =
	      proc_m2_btbTags[41:35];
      3'd6:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbTags_ETC__q11 =
	      proc_m2_btbTags[48:42];
      3'd7:
	  CASE_proc_m10_pc_BITS_4_TO_2_0_proc_m2_btbTags_ETC__q11 =
	      proc_m2_btbTags[55:49];
    endcase
  end
  always@(proc_m3_pff_rv or proc_m5_sbFlags)
  begin
    case (proc_m3_pff_rv[44:40])
      5'd0:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[0];
      5'd1:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[1];
      5'd2:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[2];
      5'd3:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[3];
      5'd4:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[4];
      5'd5:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[5];
      5'd6:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[6];
      5'd7:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[7];
      5'd8:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[8];
      5'd9:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[9];
      5'd10:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[10];
      5'd11:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[11];
      5'd12:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[12];
      5'd13:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[13];
      5'd14:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[14];
      5'd15:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[15];
      5'd16:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[16];
      5'd17:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[17];
      5'd18:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[18];
      5'd19:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[19];
      5'd20:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[20];
      5'd21:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[21];
      5'd22:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[22];
      5'd23:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[23];
      5'd24:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[24];
      5'd25:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[25];
      5'd26:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[26];
      5'd27:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[27];
      5'd28:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[28];
      5'd29:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[29];
      5'd30:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[30];
      5'd31:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d213 =
	      proc_m5_sbFlags[31];
    endcase
  end
  always@(proc_m3_pff_rv or proc_m5_sbFlags)
  begin
    case (proc_m3_pff_rv[49:45])
      5'd0:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[0];
      5'd1:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[1];
      5'd2:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[2];
      5'd3:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[3];
      5'd4:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[4];
      5'd5:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[5];
      5'd6:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[6];
      5'd7:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[7];
      5'd8:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[8];
      5'd9:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[9];
      5'd10:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[10];
      5'd11:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[11];
      5'd12:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[12];
      5'd13:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[13];
      5'd14:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[14];
      5'd15:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[15];
      5'd16:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[16];
      5'd17:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[17];
      5'd18:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[18];
      5'd19:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[19];
      5'd20:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[20];
      5'd21:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[21];
      5'd22:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[22];
      5'd23:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[23];
      5'd24:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[24];
      5'd25:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[25];
      5'd26:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[26];
      5'd27:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[27];
      5'd28:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[28];
      5'd29:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[29];
      5'd30:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[30];
      5'd31:
	  SEL_ARR_proc_m5_sbFlags_78_BIT_0_79_proc_m5_sb_ETC___d354 =
	      proc_m5_sbFlags[31];
    endcase
  end
  always@(proc_m3_pff_rv or proc_m4_rf)
  begin
    case (proc_m3_pff_rv[44:40])
      5'd0:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[31:0];
      5'd1:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[63:32];
      5'd2:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[95:64];
      5'd3:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[127:96];
      5'd4:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[159:128];
      5'd5:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[191:160];
      5'd6:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[223:192];
      5'd7:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[255:224];
      5'd8:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[287:256];
      5'd9:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[319:288];
      5'd10:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[351:320];
      5'd11:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[383:352];
      5'd12:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[415:384];
      5'd13:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[447:416];
      5'd14:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[479:448];
      5'd15:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[511:480];
      5'd16:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[543:512];
      5'd17:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[575:544];
      5'd18:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[607:576];
      5'd19:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[639:608];
      5'd20:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[671:640];
      5'd21:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[703:672];
      5'd22:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[735:704];
      5'd23:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[767:736];
      5'd24:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[799:768];
      5'd25:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[831:800];
      5'd26:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[863:832];
      5'd27:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[895:864];
      5'd28:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[927:896];
      5'd29:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[959:928];
      5'd30:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[991:960];
      5'd31:
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d265 =
	      proc_m4_rf[1023:992];
    endcase
  end
  always@(proc_m13_stalled or
	  proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_0x4___d928 or
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d921 or
	  proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_proc_ETC___d927 or
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d931 or
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d935)
  begin
    case (proc_m13_stalled[39:37])
      3'h0:
	  IF_proc_m13_stalled_23_BITS_39_TO_37_34_EQ_0x0_ETC___d944 =
	      SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d921 ?
		proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_proc_ETC___d927 :
		proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_0x4___d928;
      3'h1:
	  IF_proc_m13_stalled_23_BITS_39_TO_37_34_EQ_0x0_ETC___d944 =
	      SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d921 ?
		proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_0x4___d928 :
		proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_proc_ETC___d927;
      3'h4:
	  IF_proc_m13_stalled_23_BITS_39_TO_37_34_EQ_0x0_ETC___d944 =
	      SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d931 ?
		proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_proc_ETC___d927 :
		proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_0x4___d928;
      3'h5:
	  IF_proc_m13_stalled_23_BITS_39_TO_37_34_EQ_0x0_ETC___d944 =
	      SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d931 ?
		proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_0x4___d928 :
		proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_proc_ETC___d927;
      3'h6:
	  IF_proc_m13_stalled_23_BITS_39_TO_37_34_EQ_0x0_ETC___d944 =
	      SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d935 ?
		proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_proc_ETC___d927 :
		proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_0x4___d928;
      3'h7:
	  IF_proc_m13_stalled_23_BITS_39_TO_37_34_EQ_0x0_ETC___d944 =
	      SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d935 ?
		proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_0x4___d928 :
		proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_proc_ETC___d927;
      default: IF_proc_m13_stalled_23_BITS_39_TO_37_34_EQ_0x0_ETC___d944 =
		   proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_0x4___d928;
    endcase
  end
  always@(proc_m13_stalled or
	  proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_0x4___d928 or
	  IF_proc_m13_stalled_23_BITS_39_TO_37_34_EQ_0x0_ETC___d944 or
	  x__h62644 or y__h62528)
  begin
    case (proc_m13_stalled[31:25])
      7'h63:
	  x_15__h62477 =
	      IF_proc_m13_stalled_23_BITS_39_TO_37_34_EQ_0x0_ETC___d944;
      7'h67: x_15__h62477 = x__h62644[11:0] + proc_m13_stalled[56:45];
      7'h6F: x_15__h62477 = proc_m13_stalled[24:13] + y__h62528;
      default: x_15__h62477 =
		   proc_m13_stalled_23_BITS_24_TO_13_05_PLUS_0x4___d928;
    endcase
  end
  always@(proc_m9_pff_rv or
	  proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1035 or
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d1028 or
	  proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1034 or
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d1040 or
	  SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d1045)
  begin
    case (proc_m9_pff_rv[71:69])
      3'h0:
	  IF_proc_m9_pff_rv_port0__read__83_BITS_71_TO_6_ETC___d1054 =
	      SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d1028 ?
		proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1034 :
		proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1035;
      3'h1:
	  IF_proc_m9_pff_rv_port0__read__83_BITS_71_TO_6_ETC___d1054 =
	      SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d1028 ?
		proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1035 :
		proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1034;
      3'h4:
	  IF_proc_m9_pff_rv_port0__read__83_BITS_71_TO_6_ETC___d1054 =
	      SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d1040 ?
		proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1034 :
		proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1035;
      3'h5:
	  IF_proc_m9_pff_rv_port0__read__83_BITS_71_TO_6_ETC___d1054 =
	      SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d1040 ?
		proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1035 :
		proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1034;
      3'h6:
	  IF_proc_m9_pff_rv_port0__read__83_BITS_71_TO_6_ETC___d1054 =
	      SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d1045 ?
		proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1034 :
		proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1035;
      3'h7:
	  IF_proc_m9_pff_rv_port0__read__83_BITS_71_TO_6_ETC___d1054 =
	      SEL_ARR_proc_m4_rf_31_BITS_31_TO_0_32_proc_m4__ETC___d1045 ?
		proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1035 :
		proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1034;
      default: IF_proc_m9_pff_rv_port0__read__83_BITS_71_TO_6_ETC___d1054 =
		   proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1035;
    endcase
  end
  always@(proc_m9_pff_rv or
	  proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1035 or
	  IF_proc_m9_pff_rv_port0__read__83_BITS_71_TO_6_ETC___d1054 or
	  x__h76086 or y__h75970)
  begin
    case (proc_m9_pff_rv[63:57])
      7'h63:
	  x_13__h75921 =
	      IF_proc_m9_pff_rv_port0__read__83_BITS_71_TO_6_ETC___d1054;
      7'h67: x_13__h75921 = x__h76086[11:0] + proc_m9_pff_rv[88:77];
      7'h6F: x_13__h75921 = proc_m9_pff_rv[56:45] + y__h75970;
      default: x_13__h75921 =
		   proc_m9_pff_rv_port0__read__83_BITS_56_TO_45_0_ETC___d1035;
    endcase
  end
  always@(proc_m3_pff_rv or proc_m5_sbFlags)
  begin
    case (proc_m3_pff_rv[36:32])
      5'd0:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[0];
      5'd1:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[1];
      5'd2:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[2];
      5'd3:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[3];
      5'd4:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[4];
      5'd5:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[5];
      5'd6:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[6];
      5'd7:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[7];
      5'd8:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[8];
      5'd9:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[9];
      5'd10:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[10];
      5'd11:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[11];
      5'd12:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[12];
      5'd13:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[13];
      5'd14:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[14];
      5'd15:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[15];
      5'd16:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[16];
      5'd17:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[17];
      5'd18:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[18];
      5'd19:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[19];
      5'd20:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[20];
      5'd21:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[21];
      5'd22:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[22];
      5'd23:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[23];
      5'd24:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[24];
      5'd25:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[25];
      5'd26:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[26];
      5'd27:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[27];
      5'd28:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[28];
      5'd29:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[29];
      5'd30:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[30];
      5'd31:
	  CASE_proc_m3_pff_rv_BITS_36_TO_32_0_proc_m5_sb_ETC__q12 =
	      proc_m5_sbFlags[31];
    endcase
  end
  always@(x_5__h44387 or proc_m5_sbFlags)
  begin
    case (x_5__h44387)
      5'd0:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[0];
      5'd1:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[1];
      5'd2:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[2];
      5'd3:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[3];
      5'd4:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[4];
      5'd5:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[5];
      5'd6:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[6];
      5'd7:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[7];
      5'd8:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[8];
      5'd9:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[9];
      5'd10:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[10];
      5'd11:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[11];
      5'd12:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[12];
      5'd13:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[13];
      5'd14:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[14];
      5'd15:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[15];
      5'd16:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[16];
      5'd17:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[17];
      5'd18:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[18];
      5'd19:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[19];
      5'd20:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[20];
      5'd21:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[21];
      5'd22:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[22];
      5'd23:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[23];
      5'd24:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[24];
      5'd25:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[25];
      5'd26:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[26];
      5'd27:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[27];
      5'd28:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[28];
      5'd29:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[29];
      5'd30:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[30];
      5'd31:
	  CASE_x_54387_0_proc_m5_sbFlags_BIT_0_1_proc_m5_ETC__q13 =
	      proc_m5_sbFlags[31];
    endcase
  end
  always@(proc_m7_pff_rv$port1__read or proc_m2_btbTags)
  begin
    case (proc_m7_pff_rv$port1__read[16:14])
      3'd0:
	  CASE_proc_m7_pff_rvport1__read_BITS_16_TO_14__ETC__q14 =
	      proc_m2_btbTags[6:0];
      3'd1:
	  CASE_proc_m7_pff_rvport1__read_BITS_16_TO_14__ETC__q14 =
	      proc_m2_btbTags[13:7];
      3'd2:
	  CASE_proc_m7_pff_rvport1__read_BITS_16_TO_14__ETC__q14 =
	      proc_m2_btbTags[20:14];
      3'd3:
	  CASE_proc_m7_pff_rvport1__read_BITS_16_TO_14__ETC__q14 =
	      proc_m2_btbTags[27:21];
      3'd4:
	  CASE_proc_m7_pff_rvport1__read_BITS_16_TO_14__ETC__q14 =
	      proc_m2_btbTags[34:28];
      3'd5:
	  CASE_proc_m7_pff_rvport1__read_BITS_16_TO_14__ETC__q14 =
	      proc_m2_btbTags[41:35];
      3'd6:
	  CASE_proc_m7_pff_rvport1__read_BITS_16_TO_14__ETC__q14 =
	      proc_m2_btbTags[48:42];
      3'd7:
	  CASE_proc_m7_pff_rvport1__read_BITS_16_TO_14__ETC__q14 =
	      proc_m2_btbTags[55:49];
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        proc_m10_fEpoch <= `BSV_ASSIGNMENT_DELAY 1'd0;
	proc_m10_pc <= `BSV_ASSIGNMENT_DELAY 12'h0;
	proc_m10_pcUpdated <= `BSV_ASSIGNMENT_DELAY 1'd0;
	proc_m10_pinit <= `BSV_ASSIGNMENT_DELAY 1'd0;
	proc_m10_pinitRq <= `BSV_ASSIGNMENT_DELAY 1'd0;
	proc_m10_pinitRqOfs <= `BSV_ASSIGNMENT_DELAY 10'd0;
	proc_m10_pinitRsOfs <= `BSV_ASSIGNMENT_DELAY 10'd0;
	proc_m13_lastPc <= `BSV_ASSIGNMENT_DELAY 12'd0;
	proc_m13_stall <= `BSV_ASSIGNMENT_DELAY 1'd0;
	proc_m13_stalled <= `BSV_ASSIGNMENT_DELAY 164'd0;
	proc_m1_readRq <= `BSV_ASSIGNMENT_DELAY 1'd0;
	proc_m2_btbTags <= `BSV_ASSIGNMENT_DELAY 56'd0;
	proc_m2_btbTargets <= `BSV_ASSIGNMENT_DELAY 80'd0;
	proc_m2_btbValid <= `BSV_ASSIGNMENT_DELAY 8'd0;
	proc_m3_pff_rv <= `BSV_ASSIGNMENT_DELAY 58'h0AAAAAAAAAAAAAA;
	proc_m4_rf <= `BSV_ASSIGNMENT_DELAY 1024'd0;
	proc_m5_sbFlags <= `BSV_ASSIGNMENT_DELAY 32'd0;
	proc_m6_pff_rv <= `BSV_ASSIGNMENT_DELAY
	    165'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
	proc_m7_pff_rv <= `BSV_ASSIGNMENT_DELAY 25'd11184810;
	proc_m8_eEpoch <= `BSV_ASSIGNMENT_DELAY 1'd0;
	proc_m9_pff_rv <= `BSV_ASSIGNMENT_DELAY
	    197'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
      end
    else
      begin
        if (proc_m10_fEpoch$EN)
	  proc_m10_fEpoch <= `BSV_ASSIGNMENT_DELAY proc_m10_fEpoch$D_IN;
	if (proc_m10_pc$EN)
	  proc_m10_pc <= `BSV_ASSIGNMENT_DELAY proc_m10_pc$D_IN;
	if (proc_m10_pcUpdated$EN)
	  proc_m10_pcUpdated <= `BSV_ASSIGNMENT_DELAY proc_m10_pcUpdated$D_IN;
	if (proc_m10_pinit$EN)
	  proc_m10_pinit <= `BSV_ASSIGNMENT_DELAY proc_m10_pinit$D_IN;
	if (proc_m10_pinitRq$EN)
	  proc_m10_pinitRq <= `BSV_ASSIGNMENT_DELAY proc_m10_pinitRq$D_IN;
	if (proc_m10_pinitRqOfs$EN)
	  proc_m10_pinitRqOfs <= `BSV_ASSIGNMENT_DELAY
	      proc_m10_pinitRqOfs$D_IN;
	if (proc_m10_pinitRsOfs$EN)
	  proc_m10_pinitRsOfs <= `BSV_ASSIGNMENT_DELAY
	      proc_m10_pinitRsOfs$D_IN;
	if (proc_m13_lastPc$EN)
	  proc_m13_lastPc <= `BSV_ASSIGNMENT_DELAY proc_m13_lastPc$D_IN;
	if (proc_m13_stall$EN)
	  proc_m13_stall <= `BSV_ASSIGNMENT_DELAY proc_m13_stall$D_IN;
	if (proc_m13_stalled$EN)
	  proc_m13_stalled <= `BSV_ASSIGNMENT_DELAY proc_m13_stalled$D_IN;
	if (proc_m1_readRq$EN)
	  proc_m1_readRq <= `BSV_ASSIGNMENT_DELAY proc_m1_readRq$D_IN;
	if (proc_m2_btbTags$EN)
	  proc_m2_btbTags <= `BSV_ASSIGNMENT_DELAY proc_m2_btbTags$D_IN;
	if (proc_m2_btbTargets$EN)
	  proc_m2_btbTargets <= `BSV_ASSIGNMENT_DELAY proc_m2_btbTargets$D_IN;
	if (proc_m2_btbValid$EN)
	  proc_m2_btbValid <= `BSV_ASSIGNMENT_DELAY proc_m2_btbValid$D_IN;
	if (proc_m3_pff_rv$EN)
	  proc_m3_pff_rv <= `BSV_ASSIGNMENT_DELAY proc_m3_pff_rv$D_IN;
	if (proc_m4_rf$EN)
	  proc_m4_rf <= `BSV_ASSIGNMENT_DELAY proc_m4_rf$D_IN;
	if (proc_m5_sbFlags$EN)
	  proc_m5_sbFlags <= `BSV_ASSIGNMENT_DELAY proc_m5_sbFlags$D_IN;
	if (proc_m6_pff_rv$EN)
	  proc_m6_pff_rv <= `BSV_ASSIGNMENT_DELAY proc_m6_pff_rv$D_IN;
	if (proc_m7_pff_rv$EN)
	  proc_m7_pff_rv <= `BSV_ASSIGNMENT_DELAY proc_m7_pff_rv$D_IN;
	if (proc_m8_eEpoch$EN)
	  proc_m8_eEpoch <= `BSV_ASSIGNMENT_DELAY proc_m8_eEpoch$D_IN;
	if (proc_m9_pff_rv$EN)
	  proc_m9_pff_rv <= `BSV_ASSIGNMENT_DELAY proc_m9_pff_rv$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    proc_m10_fEpoch = 1'h0;
    proc_m10_pc = 12'hAAA;
    proc_m10_pcUpdated = 1'h0;
    proc_m10_pinit = 1'h0;
    proc_m10_pinitRq = 1'h0;
    proc_m10_pinitRqOfs = 10'h2AA;
    proc_m10_pinitRsOfs = 10'h2AA;
    proc_m13_lastPc = 12'hAAA;
    proc_m13_stall = 1'h0;
    proc_m13_stalled = 164'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    proc_m1_readRq = 1'h0;
    proc_m2_btbTags = 56'hAAAAAAAAAAAAAA;
    proc_m2_btbTargets = 80'hAAAAAAAAAAAAAAAAAAAA;
    proc_m2_btbValid = 8'hAA;
    proc_m3_pff_rv = 58'h2AAAAAAAAAAAAAA;
    proc_m4_rf =
	1024'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    proc_m5_sbFlags = 32'hAAAAAAAA;
    proc_m6_pff_rv = 165'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    proc_m7_pff_rv = 25'h0AAAAAA;
    proc_m8_eEpoch = 1'h0;
    proc_m9_pff_rv = 197'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkTop

