CONNECTALDIR?=../connectal
S2H_INTERFACES = HostRequest:Host.request
H2S_INTERFACES = Host:HostIndication

BSVFILES= Host.bsv
CPPFILES= SoftwareHost.cpp

CONNECTALFLAGS+= --mainclockperiod=16

include $(CONNECTALDIR)/Makefile.connectal

